### ISSUE TITLE
--parallel producing differing results for IBD calculations using --genome

### ISSUE THREAD

**Issue by jlc-christie** [chrchang/plink-ng#101]
Out of interest, I was calculating the speedup of IBD calculations using `--genome` on plink1.9, so I ran the command 3 times on identical data with identical parameters using it without any multithreading/parallelisation parameters, then with `--threads 16` and finally with `--parallel`. The parallel computation was computed in 16 chunks which were catenated together as documentation suggests (it was gzped). The output from the 'normal' run and the multithreaded run was identical, but the parallel file was not identical (using Unix `cmp`), I thought this may be due to ordering of the concatenated file so I did a `wc -l` to check the number of lines were identical - they weren't. 

The difference in the number of lines was not the same as the number of chunks (or a whole product of the number of chunks). In fact, the parallel file had *less* lines than the multithreaded and normal run. So it presumably isn't caused by trailing lines in each of the individual files created by the parallel command. 

For reference:
```
$ wc -l normal.genome.gz
2453 normal.genome.gz

$ wc -l multithreaded.genome.gz
2453 multithreaded.genome.gz

$wc -l parallel.genome.gz
2363 parallel.genome.gz
```

Since the order of the files in parallel doesn't directly follow the order of the files in the sequential runs, I can't diff the file to see where the differences are.

I'm unsure if this bug exists in plink2 so sorry if this has already been mentioned before (I didn't see it in a previous issue filed).

**Comment by chrchang** [comment]
Hi,

Can you provide commands and a test dataset for me to replicate what you're seeing?  Thanks.

**Comment by jlc-christie** [comment]
Hi, 

Commands used were as follows: 

#### Normal
```
plink --bfile data --extract plink.prune.in --genome gz rel-check --out normal
```

#### Multithreaded
```
plink --bfile data --extract plink.prune.in --genome gz rel-check --out multithreaded --threads 16
```

#### Parallel
Computed using a HPC cluster, using PBSPro, following is the example shell script submitted to queue. Where the -J preprocessor specifies that this is an array job, where the `PBS_ARRAY_INDEX` takes the value 1 to 16, inclusive. 
```
#!/bin/bash -l
...
#PBS -J 1-16 
...

plink --bfile data \
      --extract plink.prune.in \
      --genome gz rel-check \
      --out parallel \
      --parallel ${PBS_ARRAY_IINDEX} 16
```

I can't share the data and don't have any dummy data lying around, but it was family data containing mainly sib-pairs if that is any of help.

**Comment by chrchang** [comment]
What's the date of the plink build?

**Comment by jlc-christie** [comment]
2nd December 2018
```
PLINK v1.90b6.7 64-bit (2 Dec 2018)            www.cog-genomics.org/plink/1.9/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
```

**Comment by chrchang** [comment]
Try unzipping before counting lines.

**Comment by jlc-christie** [comment]
@chrchang that did it. That didn't even cross my mind - thanks! Still confused as to why the size of the compressed concat version would be smaller in size than the compressed original... but that's a different question completely. Thanks again!
