### ISSUE TITLE
Check for incomplete output 

### ISSUE THREAD

**Issue by labuve** [chrchang/plink-ng#105]
Hello!

Is there any nice way to test if the output of the plink2 command is complete? I wrote a loop over chromosomes to apply QC filters, but sometimes the execution of the command is halted due to some external reasons. Since the files are enormous and take a lot of time to get processed, restarting the commands is getting more and more annoying. So, I thought it would have been nice to skip chromosomes that have been fully processed and restart from "broken" chromosome. I am working with plink2 and my files (both input and output are in pgen, pvar and psam formats. My idea was the following.

Suppose the original QC code is 
`plink2 --pfile input --make-pgen --snps-only --out output`
Suppose that I know for this file that output.pgen is incomplete (its size is only 4GB when it should have been 20GB). But, of course, (i) in practice, I can't know in advance what should file size be, and (ii) I want to automate the check.
So, I thought I could check if output.pgen contains all individuals and variants that are listed in output.psam and output.pvar
`plink2 --pfile output --make-just-pvar --out test`
OR 
`plink2 --pfile output --write-snplist --out test`
Then, I could have checked output.pvar with test.pvar or output.pvar with test.snplist
However, both test.pvar and test.snplist containt exactly same information as in output.pvar. So, then this check would return me a result that output.pgen is complete (whereas, in this particular example, I know it is not).

I am fairly new to plink, so I am sorry if this is too basic question. I have tried to google both plink websites and numerous user forums, but am still unable to find nice solution for this task.  Maybe there is a function of plink that checks completeness of files, and I fail to find it.

**Comment by chrchang** [comment]
“plink2 —pfile ... —validate” can be used for this purpose.
