### ISSUE TITLE
Insufficient token during bgen conversion

### ISSUE THREAD

**Issue by ckr123tw** [chrchang/plink-ng#107]
Hi,

I was trying to convert bgen v1.2 to bed format using the following command:

plink2 --make-bed --bgen ukb_imp_chr22_v3.bgen --sample ukb_imp_chr22_v3.sample --out chr22_v3

It seems that v2.00a2 AVX2 (ran on Mac OS) was successful while the v2.00a2LM, 64-bit Intel (ran on RHEL 7.6) failed by creating psam, pvar, and pgen files.

I tried to convert pgen files into bed using the following command:

plink2 --make-bed --pfile chr22_v3-temporary --out chr22_v3

And errors popped up saying that the last line of pvar file has fewer tokens than expected.

**Comment by chrchang** [comment]
1. The first command is *supposed* to create .pgen + .psam + .pvar in plink 2.0.  It means “import to this plink version’s native format, whatever that is”.

2. You can never expect to use -temporary files; they only persist at all when something goes wrong.  And you have not provided any information, such as the preceding run’s .log or console output, to indicate why the -temporary files are there.  All I know is that it doesn’t sound like there’s a plink2 bug here, which is what this GitHub space is for reporting.

Please repost in plink2-users with enough .log/console-output and other information for someone else to precisely reproduce what you’re seeing.

**Comment by chrchang** [comment]
Sorry, “1.” in my previous reply was wrong, but “2.” stands.
