### ISSUE TITLE
Error: Variant 'rs10950839' is not biallelic

### ISSUE THREAD

**Issue by kyleberlind** [chrchang/plink-ng#108]
I'm getting this error an I was wondering if you could explain what exactly it means? Thanks!

**Comment by chrchang** [comment]
You’re doing something (e.g. creating a PLINK 1.x .bed or .bim file) which requires that all your variants have only one ALT allele, but rs10950839 has more.  One way to filter out these multiallelic variants is to add “—max-alleles 2” to your command line.

(The plink2-users Google group is a better place to ask usage questions like this.)

**Comment by 731104** [comment]
Excuse me, can I use this command in R?
