### ISSUE TITLE
Plink 1.90 --genome --within 

### ISSUE THREAD

**Issue by smlee17** [chrchang/plink-ng#111]
Hi, 
I intend to calculate pi_hat, only between samples within clusters (63 clusters), what i did was:
..
PLINK v1.90b4 64-bit (20 Mar 2017)
Options in effect:
  --genome
  --out plink9
  --vcf biallsnps_concat_rsid.recode.vcf
  --within test1.clst

--vcf: plink9-temporary.bed + plink9-temporary.bim + plink9-temporary.fam written.
94351 variants loaded from .bim file.
939 people (0 males, 0 females, 939 ambiguous) loaded from .fam.
Ambiguous sex IDs written to plink9.nosex .
--within: 63 clusters loaded, covering a total of 939 people.
Using up to 4 threads (change this with --threads).
Before main variant filters, 939 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.948238.
93351 variants and 939 people pass filters and QC.
Note: No phenotypes present.
IBD calculations complete.
Finished writing plink9.genome .

My test1.clst file format (without header): 
xx01; xx01; Asian
.....
However, the output I get is pi_hat calculation for all samples, not only within cluster (exactly same output as when no '--within' option added.
May I know why?

**Comment by chrchang** [comment]
Why not?  --within only affects a fairly small number of commands, and if you look at the --genome documentation, you'll see no mention of any --within effect.

However, you should be able to do this with a short shell script.

**Comment by smlee17** [comment]
Can you explain more on how could I write the script? Sorry for the silly question, I am a beginner in the field.
