### ISSUE TITLE
Failed to extract eigenvector(s) from GRM.

### ISSUE THREAD

**Issue by raonyguimaraes** [chrchang/plink-ng#112]
Hi there,

I'm getting this error when I try to calculate PCAs for my dataset. 

Any idea why this is happening and how to overcome this problem?

Calculating allele frequencies... 101317202427313437414448515558626568727579828689939699done.
Constructing GRM: 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
Correcting for missingness... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
Extracting eigenvalues and eigenvectors... Error: Failed to extract eigenvector(s) from GRM.

**Comment by chrchang** [comment]
I usually see this error on artificial random, unstructured data where top eigenvectors don't really exist; if it's happening on real data, that's strange and I'd like to investigate further (and possibly switch to a more reliable sequence of linear algebra operations, at least as a backup plan).

Assuming this isn't artificial data, a few quick questions:
1. Can you post the full .log file from your run?  (Also, if it isn't explicitly stated in the .log file, what operating system are you on?)
2. Is it possible for you to send me a dataset to replicate this error with?  If not, we can still proceed slowly (I can send you a debug build which prints more information about the linear algebra library function failure, you tell me what it prints, I send you another debug build following up on that result, etc.), but that'll take a while.

**Comment by chrchang** [comment]
Closing due to lack of response when I asked for more information.

**Comment by vmglynn** [comment]
I am currently facing this same issue and would appreciate some guidance. I am running PLINK v2.00a2LM AVX2 Intel on Compute Canada's infrastructure. My input files are not artificial data, but a vcf file created from mapping shallow whole genome sequencing reads to my reference genome. My .log file is as follows:

Random number seed: 1645501726
192020 MiB RAM detected; reserving 96010 MiB for main workspace.
Using up to 48 threads (change this with --threads).
--vcf: 1371471 variants scanned.
--vcf: plink_pdamPCA-temporary.pgen + plink_pdamPCA-temporary.pvar +
plink_pdamPCA-temporary.psam written.
170 samples (0 females, 0 males, 170 ambiguous; 170 founders) loaded from
plink_pdamPCA-temporary.psam.
1371471 variants loaded from plink_pdamPCA-temporary.pvar.
Note: No phenotype data present.
--extract: 42246 variants remaining.
Calculating allele frequencies... done.
42246 variants remaining after main filters.
Constructing GRM: done.
Correcting for missingness... done.
Extracting eigenvalues and eigenvectors... Error: Failed to extract eigenvector(s) from GRM.

Any guidance would be deeply appreciated, thank you in advance.

**Comment by redjay8** [comment]
> Closing due to lack of response when I asked for more information.

Hi,

Do you know why?
