### ISSUE TITLE
flag --exclude-if-info not recognized

### ISSUE THREAD

**Issue by Genutty** [chrchang/plink-ng#113]
I am trying to filter my vcf file based on imputation quality prior to outputting as PLINK binary. However, I get the following error message. I have tried both '--exclude-if-info R2<0.4' and '--extract-if-info R2>=0.4', but get the same error. Both flags are listed as options in the online documentation, but are not available through help. I have tried both PLINK v1.9 and v2.00a. 

Error: Unrecognized flag ('--extract-if-info').
For more info, try 'plink2 --help [flag name]' or 'plink2 --help | more'.

**Comment by chrchang** [comment]
Download a more recent plink2 build.
