### ISSUE TITLE
Plink 1.9 --linear fails to run with phenotype values of 0, 1, and 2

### ISSUE THREAD

**Issue by rebeccalaw** [chrchang/plink-ng#115]
Plink 1.9 --linear gives the incorrect number of phenotypes values and gives the error 'Error: --linear without --all-pheno requires a scalar phenotype.' when the phenotype column contains 0, 1, and 2.  This happens even when --missing-phenotype is set to a different number.  0, 1, and 2 are supposed to be linear scores and not missing/control/case indicators.

**Comment by chrchang** [comment]
This has always been a built-in limitation of plink, since columns don't have type labels.  A simple workaround is to translate your values to {3, 4, 5}.
