### ISSUE TITLE
--king-table-subset fails to load .kin0 file

### ISSUE THREAD

**Issue by dagola** [chrchang/plink-ng#116]
Hi @chrchang,

I'm trying to use the two-stage workflow to get a list of closely related individuals with `--king-table-subset` using the following commands:
```
plink2 --pfile all_phase3 vzs --psam phase3_corrected.psam --maf 0.2 --make-king-table --king-table-filter 0.0442 --out test_fast_relations
plink2 --pfile all_phase3 vzs --psam phase3_corrected.psam --make-king-table --king-table-filter 0.0884 --king-table-subset test_fast_relations.kin0 --out test_relations_degree_2
```
However, `plink2` fails to load the generated `test_fast_relations.kin0` with 
```
Error: Invalid header line in --king-table-subset file.
```

The head of `test_fast_relations.kin0` looks like this
```
#ID1     ID2      NSNP     HETHET    IBS0       KINSHIP
HG00120  HG00116  4057163  0.184445  0.0565326  0.087539
HG00123  HG00112  4057163  0.181133  0.0702836  0.0451506
HG00240  HG00238  4057163  0.184203  0.0625531  0.0715181
HG00542  HG00475  4057163  0.173822  0.0526452  0.0875999
HG00595  HG00584  4057163  0.173811  0.0633655  0.0592498
HG00607  HG00581  4057163  0.16915   0.0620966  0.0566572
HG00881  HG00851  4057163  0.172639  0.058134   0.0684916
HG02179  HG01795  4057163  0.172469  0.0613724  0.0636274
HG02379  HG02353  4057163  0.172249  0.0643077  0.0531969
```

I tried to remove the `#` manually, but the error is the same. Am I doing something wrong? 

I'm using `PLINK v2.00a2LM AVX2 Intel (17 Jun 2019)`.

Best,
Damian

[test_fast_relations.log](https://github.com/chrchang/plink-ng/files/3339480/test_fast_relations.log)
[test_fast_relations_degree_2.log](https://github.com/chrchang/plink-ng/files/3339505/test_fast_relations_degree_2.log)

**Comment by chrchang** [comment]
Oops, looks like I accidentally deleted the "read first line" operation... this should be fixed in commit acc917a, and I'll post updated binaries tonight.
