### ISSUE TITLE
--make-rel with 'cov' modifier does not standardize relatedness

### ISSUE THREAD

**Issue by ntraut** [chrchang/plink-ng#117]
The 'cov' modifier is to disable the division of each SNP value by its variance, but the relatedness should still be standardized so that the mean relatedness between an individual and itself is 1.

In GCTA they use those formulas to achieve this:

> --make-grm-alg 0
> The default value is 0, and the GRM is calculated using the equation sum{[(xij - 2pi)*(xik - 2pi)] / [2pi(1-pi)]} as described in Yang et al. 2010 Nat Genet. If the value = 1, the GRM will be calculated using the equation sum[(xij - 2pi)(xik - 2pi)] / sum[2pi(1-pi)]*.

**Comment by chrchang** [comment]
This is by design; 'cov' is not intended to compute a relatedness matrix at all.

**Comment by ntraut** [comment]
Hi Chang, thanks for your reply.

My confusion was coming from the plink 2.0 documentation saying that:

> Variance-standardization
> By default, the sample covariance at each variant is divided by that variant's variance (calculated from observed, or loaded, MAF). (As a consequence, very-low-MAF variants should be filtered out before performing the default computation.) To disable this and calculate a straight covariance matrix, use the 'cov' modifier.

I deduced from that that we could use the 'cov' modifier to avoid giving to much weight to very low-MAF, but in fact it is not sufficient because then the matrix is no more a relatedness matrix. We can end up to relatedness matrix by dividing everything by `mean[2pi(1-pi)]`, but is not necessarily easy to manipulate a GRM by hand. Don't you think it would be useful to implement such a feature in in plink?

**Comment by chrchang** [comment]
If you can demonstrate a clear analytical advantage for the method you're describing over what's currently implemented, you can make a plink 2.0 feature request.  As a general rule, though, plink 2.0 is focused on implementing a relatively small number of things well.  An alternative method which is only different, without being clearly better, cannot be prioritized in plink 2.0 over better implementations of calculations which are already widely used; it may still be worth optimizing, but it belongs in another program.
