### ISSUE TITLE
Feature request: barnard test instead of chi/ fisher's test

### ISSUE THREAD

**Issue by Adrianzo** [chrchang/plink-ng#118]
[I've just read about Barnard test](https://www.graphpad.com/guides/prism/7/statistics/index.htm?stat_chi-square_or_fishers_test.htm) being more powerful than fisher's and I'd like to give it a try.

Would it be so hard to implement it for plink 1.90 ?

**Comment by chrchang** [comment]
Sorry, plink 1.9 has been in maintenance-only mode since 2016.  Also, all tests of this class are essentially obsolete for GWAS because they don't support covariates.
