### ISSUE TITLE
--clump

### ISSUE THREAD

**Issue by jinghuazhao** [chrchang/plink-ng#120]
I am wondering it would be very useful to add a log10(p)-like option to --clump-p which would save some effort to prepare for a P column when it is very small but log10(P)  is manageable, e.g., LOGPVALUE ON of METAL would give such outputs. Already PLINK takes on .gz file which is a nice feature.

At the moment a specification such as --clump-p1 -9.3 are considered two options.

**Comment by chrchang** [comment]
Something along these lines will be supported by the plink 2.0 --clump implementation, but that's still some time away (merge is a higher priority...).

**Comment by chrchang** [comment]
This is now implemented.
