### ISSUE TITLE
Plink 1.9 Clump warning: No significant --clump results.  Skipping.

### ISSUE THREAD

**Issue by lumiereljy** [chrchang/plink-ng#121]
I have been getting the same warning message when I tried to run LD clumping in plink and I have also tested different p1, p2 values.

here is my terminal output:

16384 MB RAM detected; reserving 8192 MB for main workspace.
6467272 variants loaded from .bim file.
2504 people (0 males, 0 females, 2504 ambiguous) loaded from .fam.
Ambiguous sex IDs written to plink.nosex .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 2504 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.999841.
6467272 variants and 2504 people pass filters and QC.
Note: No phenotypes present.
Warning: No significant --clump results.  Skipping.

Anyone knows how to resolve this issue?

**Comment by chrchang** [comment]
1. Please include the version string and echoed command line in the terminal/log output.  You excluded practically all of the most useful information.
2. This type of usage question belongs in the plink2-users Google group (https://groups.google.com/forum/#!forum/plink2-users ).

**Comment by biyukey** [comment]
https://github.com/MRCIEU/ieugwasr/issues/36  
this will be useful
