### ISSUE TITLE
How to keep original chromosome name when the prefix is "Chr" or "chr"?

### ISSUE THREAD

**Issue by xiekunwhy** [chrchang/plink-ng#123]
Hi,

plink always delete the prefix charater "Chr" or "chr", and how to disable this auto deletion if I want to keep original chromosome names?

Best wishes,
Kun

**Comment by chrchang** [comment]
Add “—output-chr chrM” to your command line.

**Comment by xiekunwhy** [comment]
Thank you for your reply, but --output-chr chrM can't solved the problem because it recode "Chr" as "chr". And I just want to keep the "original chromosome name" because I need to use the results in downstream analysis(for example, to find genes in gtf/gff file).

**Comment by chrchang** [comment]
No major resource requires capital instead of lowercase “chr” here.  Nobody has asked me for this feature in five years.  You’re responsible for the consequences of diverging from international standards; direct support for your current workflow will not be added to plink.

**Comment by krassowski** [comment]
Would it be possible to provide a mapping for chromosome codes manually? In my use case the `--output-chr` is fine for the most part, but it does not handle alternative locus groups like `1_KI270766v1_alt` which is returned by liftover but it should be reformatted to [`KI270766.1`](https://www.ncbi.nlm.nih.gov/nuccore/KI270766.1) to match the convention used in the reference genome.
