### ISSUE TITLE
bim cannot contain multiallelic variants.

### ISSUE THREAD

**Issue by zillurbmb51** [chrchang/plink-ng#124]
Hello,
I have a list rsids (attached). I did subset 1000 genome vcf for those rsids. Now, I want to convert the new vcf into bed for downstream analysis but getting this error:
``` 
--vcf: 445 variants scanned.
--vcf: aims.panel-temporary.pgen + aims.panel-temporary.pvar +
aims.panel-temporary.psam written.
61359 samples (0 females, 0 males, 61359 ambiguous; 61359 founders) loaded from
aims.panel-temporary.psam.
445 variants loaded from aims.panel-temporary.pvar.
Note: No phenotype data present.
Writing aims.panel.fam ... done.
Writing aims.panel.bim ... 
Error: aims.panel.bim cannot contain multiallelic variants.

End time: Thu Aug 15 09:26:24 2019
```
Any help? The same error message appears when I extract a list of regions from 1000 genomes vcf . Thanks in advance. Best, Zillur
[regions.txt](https://github.com/chrchang/plink-ng/files/3505738/regions.txt)
[rsids.txt](https://github.com/chrchang/plink-ng/files/3505739/rsids.txt)

**Comment by chrchang** [comment]
This is a basic usage question that belongs in the plink2-users Google group.
