### ISSUE TITLE
plink merging with --merge-list

### ISSUE THREAD

**Issue by astulaaa** [chrchang/plink-ng#127]
I have set of BED BIM FAM files for each autosome (22) and trying to merge with --merge-list. In more than 6 hours of running PLINK the only line printed is "2064153 MB RAM detected; reserving 1032076 MB for main workspace." In this time the only outputs are -merge.fam file and completely empty log file produced. This does not seem to be normal, is there any way to speed up the merging process?

**Comment by chrchang** [comment]
General-purpose merge is pretty slow.  How large is your dataset?

The first thing I’d try, though, is forcing PLINK to use less memory.  I’m guessing you’re running on a shared machine where a single process isn’t allowed to hog an entire terabyte of RAM.  “—memory 40000” tells PLINK to limit itself to 40 GB of main-workspace memory, which is probably enough.

**Comment by astulaaa** [comment]
Small. 1 human sample in per all plink files. 22 chromosome files. Maybe around 
83282294586 B ? And yes, your guess is correct. Thank you, I will try " —memory 40000”

**Comment by astulaaa** [comment]
update: run ended in error stating insufficient memory and suggesting --memory and --parallel options

**Comment by chrchang** [comment]
The mention of --parallel in the error message indicates that you're using an old PLINK build; please update.

If the latest build still runs out of memory, the most likely cause is extremely long variant IDs, which aren't really supported by PLINK 1.9.  If that's the problem, you will need to choose a different indel naming scheme to use PLINK 1.9.

If it still runs out of memory even though you have normal-length variant IDs, can you post the full .log file from your run so I can try to replicate what you're seeing?

**Comment by Mahantesh-Biradar** [comment]
Hello, I'm in a similar situation wherein I have received the imputed data divided into ch1 to ch 22. Each chromosome has .bed, .bim and .fam files and the total size is about 175 GB. 

I would like to what is the best way to carry out QC and association analysis using these multiple files?

Thanks in advance
M

**Comment by chrchang** [comment]
Assuming each file has the same samples in the same order, you can use plink 2.0 to export to BCF, use "bcftools concat" to concatenate them, and then re-import from BCF.

This can also be done directly with a very short C program or shell script, if you read the .bed file format specification; you literally only need to skip the first three bytes of the per-chromosome .bed files.

**Comment by Mahantesh-Biradar** [comment]
Hi Chris, Thank you very much for your suggestion. Could you please point me to suitable command line documentation to perform this?

**Comment by chrchang** [comment]
plink2 --export bcf: https://www.cog-genomics.org/plink/2.0/data#export
bcftools concat: http://samtools.github.io/bcftools/bcftools.html#concat
plink2 --bcf: https://www.cog-genomics.org/plink/2.0/input#vcf

**Comment by Mahantesh-Biradar** [comment]
Thank you very much, Chris! I appreciate it
