### ISSUE TITLE
--hwe 0 still filters out variants based on hwe

### ISSUE THREAD

**Issue by bobbyjon** [chrchang/plink-ng#128]
[example.zip](https://github.com/chrchang/plink-ng/files/3718320/example.zip)

If i specify --hwe 0 it still filters variants out based on hwe. But removing --hwe will not filter variant out.
Command line that filters out based on hwe (Broken):
`plink2 --threads 2 --memory 1800 --pgen variants_split_9.pgen --pvar variants_split_9.pvar --psam variants_split_9.psam --geno 1 --hwe 0 --maf 0 --glm 'omit-ref'    --covar covar_for_plink.tsv --variance-standardize --warning-errcode --out regression_variants_split_9`

command line does not filter variant out (okay):
`plink2 --threads 2 --memory 1800 --pgen variants_split_9.pgen --pvar variants_split_9.pvar --psam variants_split_9.psam --geno 1 --maf 0 --glm 'omit-ref'    --covar covar_for_plink.tsv --variance-standardize --warning-errcode --out regression_variants_split_9`

This happens when I use version (busted): 20191009
But this is not the case when I use older version (works): 20190928 

All files are in the zip

**Comment by chrchang** [comment]
Thanks for reporting this; it should be fixed by 2747a0e.
