### ISSUE TITLE
sanity check missing (--geno) filter

### ISSUE THREAD

**Issue by dwaggott** [chrchang/plink-ng#13]
Hey - I loving the speed ups with the new plink. I wish I had this back in 08!

I'm trying to extract chrY variants from high quality females. Independent of PAR I get lot's of artefacts on exomes which are causing problems.

Calculating missing or trying to filter on missing doesn't seem to work with small datasets (n=4). That or it could be due to the handling of chrY on females. Ideas? 

[test1.zip](https://dl.dropboxusercontent.com/u/794759/github_issues/test1.zip)

```
# create the input ideally with --maf 1e-9 and --geno 1e-9
#plink --bfile xxx --chr 24  --keep high_confidence_females.txt --make-bed --out test1

# confirm that there are a mix of missing and variable positions
plink --bfile test1 --recode A --out test2

# missing/geno filtering doesn't work
plink --bfile test1 --chr 24  --geno 0.000001 --recode A --out test2
plink --bfile test1 --chr 24  --geno 0.999999 --recode A --out test2

# yup calculating missing is giving nan
plink --bfile test1  --chr 24 --miss  --out test2

```

**Comment by chrchang** [comment]
PLINK normally ignores all female Ychr genotypes.  One workaround, if your .bim file uses "24" or "chr24" to represent the Y chromosome, is to temporarily increase the number of autosomes with e.g. "--chr-set 24".
