### ISSUE TITLE
installing from source; /usr/bin/ld: cannot find -lcblas

### ISSUE THREAD

**Issue by zillurbmb51** [chrchang/plink-ng#131]
Hello, I was trying to install plink from source to activate lapack library according to : https://www.cog-genomics.org/plink/1.9/dev
 When I run ./plink_first_compile; I am getting this:
```
/usr/bin/ld: cannot find -lcblas
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [plink] Error 1

```
Any Help? Best, Zillur

**Comment by chrchang** [comment]
The instructions on that page tell you to install ATLAS first.

**Comment by zillurbmb51** [comment]
Thank you. I think I have installed it. 
`sudo yum install -y gcc gcc-c++ libstdc++ gcc-gfortran glibc glibc-devel make blas-devel lapack lapack-devel atlas-devel`
In this stage no error occurred, the error occurs  in the nest step.

**Comment by chrchang** [comment]
Are you on CentOS/RHEL 7?  I'd start by trying the upvoted ideas in https://github.com/apache/incubator-mxnet/issues/1442 .

**Comment by zillurbmb51** [comment]
Thank you very much. According to the above link I have changed the makefile. The cblas part new makefile is:
```
Makefile:BLASFLAGS ?=	-L/usr/lib64/atlas -llapack -lblas -lsatlas -latlas
Makefile.std:BLASFLAGS ?=	-L/usr/lib64/atlas -llapack -lblas -lsatlas -latlas
```
And the old one is:
```
../tools/1.9/Makefile:BLASFLAGS ?=	-L/usr/lib64/atlas -llapack -lblas -lcblas -latlas
../tools/1.9/Makefile.std:BLASFLAGS ?=	-L/usr/lib64/atlas -llapack -lblas -lcblas -latlas
```
Now I am getting this:
```
/usr/bin/ld: cannot find -latlas
collect2: error: ld returned 1 exit status
make: *** [plink] Error 1
```
What should I do now? Best, Zillur
