### ISSUE TITLE
LD-pruning output is 1-based or 0-based??

### ISSUE THREAD

**Issue by cdomsar** [chrchang/plink-ng#133]
Hi, 

I want to call genotype likelihood with ANGSD (http://www.popgen.dk/angsd/index.php/ANGSD) using a dataset of unlinked sites. ANGSD's option -sites (http://www.popgen.dk/angsd/index.php/Sites) works with 1-based genomic and chromosomal positions. I have generated a dataset of sites pruned for linkage disequilibrium with option --indep-pairwise 50 5 0.5 in PLINK v1.9 and have two outputs (dataset.prune.in and dataset.prune.out).

I would like to use the output dataset of unlinked sites (dataset.prune.in) as -sites for ANGSD to run. However, I haven't found anywhere (neither at https://www.cog-genomics.org/plink/1.9/ld nor at http://zzz.bwh.harvard.edu/plink/summary.shtml nor in FAQ) if the output of PLINK is 0-based or 1-based and I don't know if I should transform this output to work. Is it 0-based or 1-based?

Best regards and thanks in advance,

Carlos

**Comment by chrchang** [comment]
The answer is "neither".  Have you looked at the output files??

**Comment by cdomsar** [comment]
I have! Here is the output of both files:

head genome.prune.in
chr01_4
chr01_5
chr01_6
chr01_7
chr01_8
chr01_9
chr01_26
chr01_34
chr01_37
chr01_42

head genome.prune.out
chr01_35
chr01_111
chr01_321
chr01_450
chr01_451
chr01_463
chr01_636
chr01_937
chr01_986
chr01_1045

tail genome.prune.in
chr38_2607700
chr38_2607845
chr38_2608056
chr38_2608154
chr38_2608642
chr38_2608813
chr38_2609061
chr38_2609260
chr38_2609300
chr38_2609415

tail genome.prune.out
chr38_2606766
chr38_2607049
chr38_2607168
chr38_2607614
chr38_2608038
chr38_2608299
chr38_2608430
chr38_2608647
chr38_2608723
chr38_2608930

None of them matches the first nor last position of the genome (chr38, 23914537). I would need to know the positions of these SNPs to feed my ANGSD call. Is prune.in not the correct file to do so?

Thanks in advance

**Comment by chrchang** [comment]
Perhaps I should also have said "Have you looked at the input files?"

The point is that *you* fed variant IDs like "chr01_4" and "chr01_35" to PLINK as *input*.  You need to look at the program that originally generated those IDs, which wasn't PLINK.
