### ISSUE TITLE
PLINK make CNV map function

### ISSUE THREAD

**Issue by oalavijeh** [chrchang/plink-ng#134]
Dear plink team, 

I am trying to run the following:

plink --cnv-list mydata.cnv --cnv-make-map using Plink 1.9

I run into the message --cnv-list is unfinished or untested, please use developmental build. 

I was wondering how one would access this build? I am running a rare CNV analysis on a disease and control population. 

Many thanks

Omid

**Comment by chrchang** [comment]
For CNV-related features, it's better to just use PLINK 1.07 for now.

(I had intended to opportunistically build them out when I encountered CNV datasets in my day-to-day work, but that just hasn't happened.  So now the plan is to backfill them once PLINK 2.0 merge is working sometime in 2020.)

**Comment by oalavijeh** [comment]
Many thanks! Works a treat
