### ISSUE TITLE
failure to read uncompressed .bcf through pipe

### ISSUE THREAD

**Issue by mzaki-jp** [chrchang/plink-ng#136]
In the latest stable build, plink cannot read uncompressed BCF file through pipe.
Compressed BCF is OK, and uncompressed BCF is also OK when it is read from filesystem.
For VCF, both compressed and uncompressed, plink can read them both from pipe and filesystem.
I guess it would be nice for performance if we can provide uncompressed bcf through pipe.

This is reproduced on the combinations of:
Linux 3.10.0 x86_64 / plink v1.90b6.10 64-bit / bcftools 1.10
FreeBSD 11.3-RELEASE-p5 amd64 / plink v1.90b6.15 64-bit / bcftools 1.9

How to repeat:
$ wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz -O mt.vcf.gz # 1KGP data for testing (ca. 206kb) 
$ bcftools view -Ob mt.vcf.gz >mt.bcf; plink --bcf mt.bcf --out test # OK
$ bcftools view -Ou mt.vcf.gz >mt.bcf; plink --bcf mt.bcf --out test # OK
$ bcftools view -Ob mt.vcf.gz |plink --bcf /dev/stdin --out test # OK
$ bcftools view -Ou mt.vcf.gz |plink --bcf /dev/stdin --out test
PLINK v1.90b6.15 64-bit (21 Jan 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to test.log.
Options in effect:
  --bcf /dev/stdin
  --out test

65405 MB RAM detected; reserving 32702 MB for main workspace.

Error: File read failure.

**Comment by chrchang** [comment]
As a general rule, plink does not promise support for piped input.

However, the infrastructure is now in place to add efficient support for this in plink 2.0.  I'll try to have that working within the next few days.

**Comment by chrchang** [comment]
On second thought, no, piped --bcf won't work in plink 2.0 due to how support for multiallelic, phased, and dosage data works: there isn't enough information in the BCF header to perform the conversion easily in one pass.  However, the 2-pass conversion will be highly optimized.

**Comment by chrchang** [comment]
plink2 --bcf is now implemented, and has ~5x the throughput of plink 1.9 --bcf on a typical multicore machine in my testing.
