### ISSUE TITLE
--ld-window-kb parameter does not seem to work with features --r2/--r

### ISSUE THREAD

**Issue by onaret** [chrchang/plink-ng#137]
Hi,

When using the --r2/--r features, regardless of the value I pass to the parameter --ld-window-kb, I always get the same list of SNPs in a range of 500 **b**ases (not even kb).
I am doing it on raw 1KG

If this is correct, I would be very grateful to be indicated an intermediate version of plink where it works.

Thanks,

Olivier

**Comment by yk-tanigawa** [comment]
Hi Olivier, 

You may want to increase the window size (`--ld-window`).

As a user, I'm also confused with the default value of 10, which seems like the default behavior from PLINK 1.0x

Best,
Yosuke

**Comment by chrchang** [comment]
@yk-tanigawa is correct; you need to add e.g. "--ld-window 9999999" to your command line to get the behavior you expect.  (Yes, this default behavior will be changed in PLINK 2.0.)

**Comment by onaret** [comment]
Many thanks! :+1:
