### ISSUE TITLE
Error when installing pgenlibr locally

### ISSUE THREAD

**Issue by Keisarinn** [chrchang/plink-ng#138]
Was able to install cindex locally(all 2.0) with the command

devtools::install_local(path=$HOME,subdir="2.0/cindex")

However, 

devtools::install_local(path=$HOME,subdir="2.0/pgenlibr")

gives me the error

![image](https://user-images.githubusercontent.com/14221332/80202559-57946680-8615-11ea-82a7-384d747953b1.png)

I noticed that in the 2.0/include there wasn´t any zstd.h so I copied a file with the same name from 2.0/zstd/lib with the same result. I have installed zstd, i.e.

zstd --version
yields
*** zstd command line interface 64 bits v1.4.4, by Yann Collet ***

**Comment by chrchang** [comment]
This requires the zstd library, not just a standalone command-line tool, to be installed on your system.

**Comment by kulmsc** [comment]
I have received an identical error.

I believe I have fully installed the zstd library, however it was to a local directory.  Specifically I downloaded the zip file from https://github.com/facebook/zstd, then:

`unzip zstd-dev.zip`
`cd zstd-dev`
`make install PREFIX=/home/my_username/Programs`

Perhaps when pgenlibr installs it only looks in the default zstd location (something like /usr/...) and not my personal Programs directory.  Would it be possible to include an option to specify where the zstd library is held?

**Comment by chrchang** [comment]
Hmm, enough people are having trouble with this that it makes sense to switch back to just using the copy of the zstd source code included under plink-ng/2.0/ for now, despite the duplication and longer compile time.  I'll do that today, while leaving a non-default way to use the system-installed zstd.

**Comment by chrchang** [comment]
This should be fixed as of c23c533 ; sorry about the delay.
