### ISSUE TITLE
--vcf-half-call

### ISSUE THREAD

**Issue by hou** [chrchang/plink-ng#141]
Hello Chris, I have one quick question about PLINK2. Based on this [link](https://www.cog-genomics.org/plink/2.0/input#vcf_half_call) seems like plink2 will error out when it sees half-calls (_By default (mode 'error'/'e'), PLINK errors out and reports the line number of the anomaly_). But I actually was able to convert my VCF file to pgen format. I am pretty sure in my VCF file, there are some half-calls in it.

Could you please clarify? I am interested to know how PLINK2 handles half-calls by default.

Thanks,

Liping

**Comment by chrchang** [comment]
Please post a .log file.

**Comment by hou** [comment]
> Please post a .log file.

Here you go:

PLINK v2.00a2LM 64-bit Intel (21 Aug 2019)
Options in effect:
  --make-pgen
  --out test
  --var-filter
  --vcf tem.vcf.gz

Hostname: domino-run-5eaca50a4cedfd0008778ce1
Working directory: /efs/ukb-storage/domino_work/houl2_work/Data/wes/ukb_300k/vcf/dp15_gq20_sb/ab_filtered/final
Start time: Sat May  2 05:40:33 2020

Random number seed: 1588398033
245854 MiB RAM detected; reserving 122927 MiB for main workspace.
Using up to 32 threads (change this with --threads).
--vcf: 4422 variants scanned.
--vcf: test-temporary.pgen + test-temporary.pvar + test-temporary.psam written.
302342 samples (0 females, 0 males, 302342 ambiguous; 302342 founders) loaded
from test-temporary.psam.
3435 out of 4422 variants loaded from test-temporary.pvar.
Note: No phenotype data present.
3435 variants remaining after main filters.
Writing test.psam ... done.
Writing test.pvar ... done.
Writing test.pgen ... done.

End time: Sat May  2 05:41:31 2020

**Comment by hou** [comment]
> Please post a .log file.

Here you go:

PLINK v2.00a2LM 64-bit Intel (21 Aug 2019)
Options in effect:
  --make-pgen
  --out test
  --var-filter
  --vcf tem.vcf.gz

Hostname: domino-run-5eaca50a4cedfd0008778ce1
Working directory: /efs/domino_work/houl2_work/Data/wes/vcf/dp15_gq20_sb/ab_filtered/final
Start time: Sat May  2 05:40:33 2020

Random number seed: 1588398033
245854 MiB RAM detected; reserving 122927 MiB for main workspace.
Using up to 32 threads (change this with --threads).
--vcf: 4422 variants scanned.
--vcf: test-temporary.pgen + test-temporary.pvar + test-temporary.psam written.
302342 samples (0 females, 0 males, 302342 ambiguous; 302342 founders) loaded
from test-temporary.psam.
3435 out of 4422 variants loaded from test-temporary.pvar.
Note: No phenotype data present.
3435 variants remaining after main filters.
Writing test.psam ... done.
Writing test.pvar ... done.
Writing test.pgen ... done.

End time: Sat May  2 05:41:31 2020

**Comment by chrchang** [comment]
Rerun with a newer build; there was a --vcf-half-call bugfix in February.

**Comment by hou** [comment]
> Rerun with a newer build; there was a --vcf-half-call bugfix in February.

Great, thanks! Glad to hear that bug has been fixed.
