### ISSUE TITLE
Dosage16ToDoubles question

### ISSUE THREAD

**Issue by jpritikin** [chrchang/plink-ng#142]
2.0/pgenlib_ffi_support.cc lines 177-188 are,

````
void Dosage16ToDoubles(const double* geno_double_pair_table, const uintptr_t* genoarr, const uintptr_t* dosage_present, const uint16_t* dosage_main, uint32_t sample_ct, uint32_t dosage_ct, double* geno_double) {
  GenoarrLookup16x8bx2(genoarr, geno_double_pair_table, sample_ct, geno_double);
  if (dosage_ct) {
    const uint16_t* dosage_main_iter = dosage_main;
    uintptr_t sample_uidx_base = 0;
    uintptr_t cur_bits = dosage_present[0];
    for (uint32_t dosage_idx = 0; dosage_idx != dosage_ct; ++dosage_idx) {
      const uintptr_t sample_uidx = BitIter1(dosage_present, &sample_uidx_base, &cur_bits);
      geno_double[sample_uidx] = S_CAST(double, *dosage_main_iter++) * 0.00006103515625;
    }
  }
}
````

I was surprised to find that `GenoarrLookup16x8bx2` writes `geno_double` and then when `dosage_ct>0` much of the data just written to `geno_double` is overwritten. Is this working as intended? Given that the code is generally super-optimized, is it necessary to write `geno_double` almost twice?

**Comment by chrchang** [comment]
If you look at e.g. UK Biobank data, non-integer dosages are somewhat sparse.  This function tends to be more efficient on real datasets that don't involve catastrophic QC failures than what you have in mind.

**Comment by jpritikin** [comment]
Ah, I didn't realize that was the case. Interesting. Thank you!
