### ISSUE TITLE
Keeping Chromosome Codes in VCF, Deleting 0

### ISSUE THREAD

**Issue by katimbach** [chrchang/plink-ng#143]
Hi, 

Forgive me if this is a silly question, but I am trying to generate a genotyping VCF in order to genotype scRNA-seq data in the form of BAM files using demuxlet (https://github.com/statgen/demuxlet). However, demuxlet is very strict about the concordance between the chromosome labeling and order between the VCF and BAM files, and I am running into issues getting them to match. The BAM files are directly from 10X and contain MT, X, Y and are ordered lexicographically. While I was able to reorder the VCF chromosomes in this way, I am running into issues now because of the chromosome coding used by plink:

     X    X chromosome                    -> 23
     Y    Y chromosome                    -> 24
     XY   Pseudo-autosomal region of X    -> 25
     MT   Mitochondrial                   -> 26

Is there a way to maintain the original labeling in the VCF file, or change the labels of these to match the BAM file? Also, can I somehow get rid of the chromosome 0 reads since these will not be present in the BAM files either? This also coincides with what I posted to demuxlet (https://github.com/statgen/demuxlet/issues/65).

Any insight is greatly appreciated, as I am just an undergrad and very new to plink and genotyping in general. Thanks very much for all the help in advance!

**Comment by chrchang** [comment]
See [--output-chr](https://www.cog-genomics.org/plink/2.0/data#irreg_output)

**Comment by katimbach** [comment]
Thank you! I was able to recreate a VCF file using the following adjustments (if anybody else is struggling with the same issue)

plink --bfile merged_binary_updated --recode vcf-iid --out merged_vcf_new --output-chr MT --not-chr 0 XY
