### ISSUE TITLE
Warning: Skipping --logistic since # variables >= # samples

### ISSUE THREAD

**Issue by KarthickRajaNarayanan** [chrchang/plink-ng#144]
Hi,

I'm trying to run the --logistic command in plink along with covariate file for my 10 samples. But it's throwing the following error.

Options in effect:
  --allow-no-sex
  --bfile ZIFO_BROAD_Array_Final_10
  --covar covar_mds_new.txt
  --hide-covar
  --logistic
  --out binary_logistic_results

Note: --hide-covar flag deprecated.  Use e.g. "--linear hide-covar".
32167 MB RAM detected; reserving 16083 MB for main workspace.
324307 variants loaded from .bim file.
10 people (6 males, 3 females, 1 ambiguous) loaded from .fam.
Ambiguous sex ID written to binary_logistic_results.nosex .
10 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
--covar: 8 covariates loaded.
Before main variant filters, 10 founders and 0 nonfounders present.
Calculating allele frequencies... done.
324307 variants and 10 people pass filters and QC.
Among remaining phenotypes, 5 are cases and 5 are controls.
Warning: Skipping --logistic since # variables >= # samples.

Can someone please help me out?

Regards,
Karthick

**Comment by chrchang** [comment]
You don't have enough samples for this analysis.
