### ISSUE TITLE
How to calculate LD in spesific borderline, like Chr22:42721342-48721342?

### ISSUE THREAD

**Issue by lymlin** [chrchang/plink-ng#147]
Dear professors,
I want to calculate LD in specific borderlines, like Chr22:42721342-48721342. But there seems no relevant command like region in bcftools.  We consider plink tools more suitable if there is a method to figure this out. 
Lym

**Comment by chrchang** [comment]
See plink 1.9's --r/--r2 flag: https://www.cog-genomics.org/plink/1.9/ld#r

Sample command:
plink \
  --bcf my.bcf \
  --r2 \
  --chr 22 \
  --from-bp 42721342 \
  --to-bp 48721342 \
  --ld-window 999999

You may also want to change the --ld-window-kb and --ld-window-r2 settings.

**Comment by lymlin** [comment]
Thanks, ChrChang.  
There is another question about plink.
I want to select independent SNPs. And I found that Plink --extract could not obtain LD r2 for each pair in an SNP list file. 

./plink --bfile KGref/Chr22.Eur --noweb  --r2  --extract ENSG00000100376.snp1  --ld-window-r2 0 --out ENSG00000100376.A

For example, the pair, rs138826351-rs189604072, was not calculated.

However, when I filtered some SNPs, the remaining SNPs showed the LD of rs138826351-rs189604072. 

I thought whether I changed to use --ld-snp-list helpful. 
./plink --bfile KGref/Chr22.Eur --noweb  --r2  --extract ENSG00000100376.snp1  --ld-window-r2 0 --out ENSG00000100376.A
The Linux command returned an Error: Duplicate ID 'rs10656307',  Although, there was not an SNP named 'rs10656307'. 

How can I fix this?

**Comment by chrchang** [comment]
Note the "--ld-window 999999" in my command line.

**Comment by lymlin** [comment]
Thanks, chrchang. Now, I know it is due to the default parameters.

**Comment by lymlin** [comment]
Dear chrchang,
How could I read the bin LD file produced by plink? For example, in Linux or R.
