### ISSUE TITLE
ERROR: compilation failed for package ‘pgenlibr’

### ISSUE THREAD

**Issue by gustavahlberg** [chrchang/plink-ng#148]
Having problems with install pgenlibr with either clang or gcc:

Describe the bug
make: *** [libdeflate/lib/adler32.o] Error 1
ERROR: compilation failed for package ‘pgenlibr’

removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pgenlibr’
Error: Failed to install 'pgenlibr' from GitHub:
To Reproduce
install_github("chrchang/plink-ng", subdir="/2.0/pgenlibr")

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6
Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Compiler [e.g gcc]
gcc-9

**Comment by gustavahlberg** [comment]
With clang:

pvar.cpp:107:45: error: a space is required between consecutive right angle brackets (use '> >')
  XPtr<class RPvar> rp = as<XPtr<class RPvar>>(pvar[1]);
                                            ^~
                                            > >
pvar.cpp:117:45: error: a space is required between consecutive right angle brackets (use '> >')
  XPtr<class RPvar> rp = as<XPtr<class RPvar>>(pvar[1]);
                                            ^~
                                            > >
pvar.cpp:127:45: error: a space is required between consecutive right angle brackets (use '> >')
  XPtr<class RPvar> rp = as<XPtr<class RPvar>>(pvar[1]);
                                            ^~
                                            > >
3 errors generated.
make: *** [pvar.o] Error 1
ERROR: compilation failed for package ‘pgenlibr’
* removing ‘/usr/local/lib/R/4.0/site-library/pgenlibr’
* restoring previous ‘/usr/local/lib/R/4.0/site-library/pgenlibr’
Error: Failed to install 'pgenlibr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/1c/rzbgktfd1j71g7ggz48ft2880000gn/T//Rtmp6jQtCk/file166bcf17035b/pgenlibr_0.2.tar.gz’ had non-zero exit status

**Comment by chrchang** [comment]
Should be fixed by eb622d8 ; let me know if you still have any problems.

**Comment by gustavahlberg** [comment]
Yes, got it. Thank you very much!
