### ISSUE TITLE
ref alt alleles

### ISSUE THREAD

**Issue by jawzman7** [chrchang/plink-ng#149]
I made PLINK files from bgen files and used the option ref-last, yet when I run a frequency check in PLINK2, the header indicates that it switches the ref and alt alleles and the alt allele frequency given it the ref alleles...it makes no sense?? why have the option if it will switch them in the output...???

**Comment by chrchang** [comment]
Can you post .log files clarifying exactly what you're talking about here?

**Comment by jawzman7** [comment]
PLINK v2.00a2LM AVX2 Intel (10 Aug 2019)
Options in effect:
  --bgen MEGA_chr21.bgen ref-last
  --make-bed
  --missing-code -9
  --out MEGA_chr21
  --oxford-single-chr 21
  --sample mega4.sample

Hostname: tiamat.vampire
Working directory: /data1/data/BioVU_MEGA_2020/BGEN_files
Start time: Mon Jul 13 10:25:30 2020

Random number seed: 1594653930
1031764 MiB RAM detected; reserving 515882 MiB for main workspace.
Allocated 386911 MiB successfully, after larger attempt(s) failed.
Using up to 72 threads (change this with --threads).
--bgen: 531276 variants detected, format v1.2.
92300 samples imported from .sample file to MEGA_chr21-temporary.psam .
--bgen: MEGA_chr21-temporary.pgen + MEGA_chr21-temporary.pvar written.
92300 samples (0 females, 0 males, 92300 ambiguous; 92300 founders) loaded from
MEGA_chr21-temporary.psam.
531276 variants loaded from MEGA_chr21-temporary.pvar.
1 binary phenotype loaded (0 cases, 92300 controls).
Writing MEGA_chr21.fam ... done.
Writing MEGA_chr21.bim ... done.
Writing MEGA_chr21.bed ... done.

End time: Mon Jul 13 10:27:43 2020

PLINK v2.00a2LM AVX2 Intel (10 Aug 2019)       www.cog-genomics.org/plink/2.0/
(C) 2005-2019 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --bfile MEGA_chr21
  --freq

Start time: Mon Jul 13 14:51:10 2020
1031764 MiB RAM detected; reserving 515882 MiB for main workspace.
Using up to 72 threads (change this with --threads).
92300 samples (0 females, 0 males, 92300 ambiguous; 92300 founders) loaded from
MEGA_chr21.fam.
531276 variants loaded from MEGA_chr21.bim.
1 binary phenotype loaded (0 cases, 92300 controls).
Calculating allele frequencies... done.
--freq: Allele frequencies (founders only) written to plink2.afreq .

This is the output for one of the markers
#CHROM  ID      REF     ALT     ALT_FREQS       OBS_CT
21      21:10624615:G:A A       G       0.768526        2402

yet I had set to ref last so below the ref was G...and freq of alt A is 0.17
SNP     REF(0)  ALT(1)  ALT_Frq MAF     AvgCall Rsq     Genotyped       LooRsq  EmpR    EmpRsq  Dose0   Dose1
21:10624615:G:A G       A       0.17151 0.17151 0.83181 0.04065 Imputed -       -       -       -       -

**Comment by chrchang** [comment]
What you've posted so far implies that your error was using ref-last instead of ref-first, and there's no problem with PLINK.

**Comment by jawzman7** [comment]
I tried initially without the option and the subsequent frequency files were wrong...I thought the option was to designate the output files and not the input file, ie aren't all bgen files ref first? 
So I guess the option is not how you want the resultant bed file to be...but the way the input is I guess....

**Comment by chrchang** [comment]
No, the default behavior is NOT ref-first.  You need to explicitly specify it.
