### ISSUE TITLE
Wrong minor allele frequency results.

### ISSUE THREAD

**Issue by xiekunwhy** [chrchang/plink-ng#151]
Hi,
plink give 0 maf when minor allele frequecy is very small (but not 0)
1	1105317	_rs11811498_	G	A	.	.	PR	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	**0/1**	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	./.	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0 0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0

grep _rs11811498_ HapMap_3_r3_1.frq
   1  rs11811498    A    G            **0**      222

and I want to keep all poly sites only, any method to realize using plink?

Best wishes,
Kun

**Comment by xiekunwhy** [comment]
gcta gives me the exactly right results,

gcta64 --bfile HapMap_3_r3_1 --freq --out HapMap_3_r3_1_poly2
grep rs11811498 HapMap_3_r3_1_poly2.frq
1	_rs11811498_	1105317	A	G	0.00304878	328

**Comment by chrchang** [comment]
See https://www.cog-genomics.org/plink/1.9/filter#nonfounders .
