### ISSUE TITLE
Warning: Skipping --linear/--logistic since phenotype is constant.

### ISSUE THREAD

**Issue by duzc19940423** [chrchang/plink-ng#154]
Hi, the following are my command, running log and the first few row of my merge.fam file: 

**command**:
`plink --bfile merge -assoc --adjust --logistic --out ./gwas_test/NX_vs_XJ`
**running log**
>PLINK v1.90b6.18 64-bit (16 Jun 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ./gwas_test/NX_vs_XJ.log.
Options in effect:
  --adjust
  --assoc
  --bfile merge
  --logistic
  --out ./gwas_test/NX_vs_XJ

>112715 MB RAM detected; reserving 56357 MB for main workspace.
389381 variants loaded from .bim file.
148 people (73 males, 75 females) loaded from .fam.
148 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 148 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.998328.
389381 variants and 148 people pass filters and QC.
Among remaining phenotypes, 109 are cases and 39 are controls.
Writing C/C --assoc report to ./gwas_test/NX_vs_XJ.assoc ...
done.
--adjust: Genomic inflation est. lambda (based on median chisq) = 1.05577.
--adjust values (389334 variants) written to
./gwas_test/NX_vs_XJ.assoc.adjusted .
Warning: Skipping --linear/--logistic since phenotype is constant.

**merge.fam file**

> 10005486801 10005486801 0 0 2 2
10019439574 10019439574 0 0 2 2
10040280280 10040280280 0 0 2 2
10044641271 10044641271 0 0 1 2
10045574515 10045574515 0 0 1 2
10054754894 10054754894 0 0 1 2
10092474492 10092474492 0 0 1 1
10100269126 10100269126 0 0 1 1
10103279430 10103279430 0 0 1 2
10108367327 10108367327 0 0 2 2

According to *.fam file and running log, it is obviously that I have labeled case and control at the sixth columns. Therefore I wonder why this warning occured, Are there any other possible reason? 
Thank you. Look forward to your reply.

**Comment by chrchang** [comment]
I'm unable to replicate this behavior.  Can you send me a toy dataset (could contain just 1-2 variants) that I can use to reproduce what you're seeing?

**Comment by duzc19940423** [comment]
@chrchang Thanks for your reply. I have send the whole data (about 8M) to your email (chrchang@alumni.caltech.edu). Please check.

**Comment by chrchang** [comment]
Thanks, bug should be fixed as of adcfcff .

**Comment by duzc19940423** [comment]
@chrchang appreciate it! It works well! 
There is an additional question. I have batch of data, but only the data I send to you have this warning. should I rerun the rest?

**Comment by chrchang** [comment]
That shouldn't be necessary.  The one possible exception is if you were performing --logistic permutation tests; very few users do this.

**Comment by duzc19940423** [comment]
Thank you, I got it!
