### ISSUE TITLE
Question about PCA

### ISSUE THREAD

**Issue by duzc19940423** [chrchang/plink-ng#156]
Hi,  I wonder if I can get the original eigenvector instead of transformed data (`.eigenvec`)?
Actually, I want use the PCA transformed data to build a machine learning model. my purpose is that if there is a new sample, I can use the eigenvector to transform the new sample without changing the reference data. 
So are there any method I can use to achieve this goal? And how the original data are normalized (e.g. centralized by SNP)?

**Comment by chrchang** [comment]
1. See https://www.cog-genomics.org/plink/2.0/score#pca_project .
2. They are mean-centered and variance-standardized.

**Comment by duzc19940423** [comment]
Thank you！I got it!
