### ISSUE TITLE
Error: test.haps has an odd number of tokens in the first line.

### ISSUE THREAD

**Issue by duzc19940423** [chrchang/plink-ng#157]
Hi, 
When I want to import `.haps`  to `PLINK v2.00a3LM 64-bit Intel (28 Oct 2020)`, the error occured.
My command is `plink2 --haps test.haps --legend test.legend 26 --make-bed --out test`.
the running log is as follow.
```
PLINK v2.00a3LM 64-bit Intel (28 Oct 2020)
Options in effect:
  --haps test.haps
  --legend test.legend 26
  --make-bed
  --out test

Hostname: bioinfo-yxk.laso
Working directory: /home/duzc/work/2.ancestry_v2/2.snp_selection/2.tagSNP_Japonica/Dat/1.convert2haps_legend
Start time: Wed Nov  4 19:38:25 2020

Random number seed: 1604489905
112715 MiB RAM detected; reserving 56357 MiB for main workspace.
Allocated 31700 MiB successfully, after larger attempt(s) failed.
Using up to 40 threads (change this with --threads).
Error: test.haps has an odd number of tokens in the first line. (With --haps +
--legend, the .haps file is expected to have no header columns.)

End time: Wed Nov  4 19:38:25 2020
```

the first few rows of `.haps` and `.legend` are:

> 1 1:15211:T:G 15211 T G 0 0 0 0 0 0 0  
> 1 1:15820:G:T 15820 G T 2 2 2 2 2 2 2 2
> 1 1:91515:A:C 91515 A C 0 0 0 0 0 0 0 1
> 1 1:91536:G:T 91536 G T 0 0 0 0 0 0 0 1
> 1 1:91581:G:A 91581 G A 0 0 0 0 0 0 0 1
> 1 1:95440:C:G 95440 C G 0 0 0 0 0 0 0 1
> 1 1:104186:T:C 104186 T C 0 0 0 0 0 0 0 0
> 1 1:536095:C:T 536095 C T 0 0 0 0 0 0 0 1
> 1 1:564621:C:T 564621 C T 0 0 0 0 0 0 0 1
> 1 1:565006:T:C 565006 T C 2 2 2 2 2 2 2 1

> id position a0 a1
> 1:15211:T:G 15211 T G
> 1:15820:G:T 15820 G T
> 1:91515:A:C 91515 A C
> 1:91536:G:T 91536 G T
> 1:91581:G:A 91581 G A
> 1:95440:C:G 95440 C G
> 1:104186:T:C 104186 T C
> 1:536095:C:T 536095 C T
> 1:564621:C:T 564621 C T

both of .haps and .legend files are whitespace-delimited.
looking forward to your reply.

**Comment by chrchang** [comment]
Why do you think that is a valid .haps file?

**Comment by duzc19940423** [comment]
Sorry, a stupid question. 
Anyway, it helps a lot, thank you.
