### ISSUE TITLE
Option --update-sex no longer works after PLINK v2.00a2LM

### ISSUE THREAD

**Issue by kaboroevich** [chrchang/plink-ng#159]
When converting from VCF, all releases after PLINK v2.00a2LM 64-bit Intel (7 Jan 2019) completely ignore the --update-sex option.  The file is not even read as when I replaced the file name with a nonexistent file no error was reported.

**Comment by chrchang** [comment]
I just tried simple --vcf --update-sex and --vcf --update-sex --make-pgen commands, and both had the expected behavior.  Can you please post a log file illustrating what you mean?

**Comment by kaboroevich** [comment]
Sorry. I must have been doing something wrong. There's no explicit "Error: Failed to open <file>" error so I assumed the files were regenerated, but in fact, plink2 exited before generating the files.
