### ISSUE TITLE
[bug report]`--const-fid` not work when covert bgen to vcf.

### ISSUE THREAD

**Issue by wavefancy** [chrchang/plink-ng#160]
Hi Christopher,

It seems plink2 covert bgen to vcf is not working for setting family id. 
```
# PLINK v2.00a3LM 64-bit Intel (28 Oct 2020)
Options in effect:
  --bgen test.bgen ref-last
  --const-fid FF
  --export vcf bgz
  --memory 3500
  --out out
  --oxford-single-chr 19
  --sample bgen_sample
  --threads 10
```

Thanks much for checking in advance!

Best regards
Wallace

**Comment by chrchang** [comment]
Not a bug: --const-fid only applies when importing single-part sample IDs.  If your --sample file already has two-part IDs, --const-fid does not apply (but you can e.g. change the first column of the sample file with a shell script one-liner).

**Comment by wavefancy** [comment]
But is this more consistent if also in effect if already in two parts IDs? and would be a nice feature ` If '0' (the default), no FID column is created.` if I really want to get rid of the family id? Otherwise, the current document is a little bit confusing. However, really defer to you how you want to implement this. Thank you very much!

```
--const-fid [ID]    : Set all FIDs to the given constant.  If '0' (the
                      default), no FID column is created.
```

Best regards
Wallace

**Comment by chrchang** [comment]
I will edit the documentation to clarify that it's specific to importing.
