### ISSUE TITLE
[--het] who can tell me the --het algorithm

### ISSUE THREAD

**Issue by fzuguo** [chrchang/plink-ng#163]
this is mv vcf infos:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A	B
pseudoChr01	53116	.	A	G	5187.77	PASS	.	GT	0/1	1/1
pseudoChr01	53139	.	C	T	4126.3	PASS	.	GT	0/1	1/1
pseudoChr01	53169	.	C	T	3413.43	PASS	.	GT	1/1	0/0
pseudoChr01	53215	.	G	T	2982.04	PASS	.	GT	0/0	0/1
pseudoChr01	53231	.	G	T	3002.19	PASS	.	GT	1/1	0/0
pseudoChr01	53383	.	T	C	5452.85	PASS	.	GT	0/0	0/1
pseudoChr01	53411	.	G	A	2409.74	PASS	.	GT	0/1	1/1
pseudoChr01	53413	.	A	T	2346.46	PASS	.	GT	1/1	0/0
pseudoChr01	53414	.	A	T	2346.46	PASS	.	GT	0/0	0/1

my command:
plink --vcf test2.vcf --recode --out snp --double-id --allow-extra-chr
plink --noweb --file snp --het --out result --allow-extra-chr

my result:
FID  IID       O(HOM)       E(HOM)        N(NM)            F
   A    A            6         5.25            9          0.2
   B    B            6         5.25            9          0.2

why E(HOM) equal 5.25 
 According to my understanding ： it should be aa+AA = 9*0.5*0.5 + 9*0.5*0.5 = 0.45
can you help me?

**Comment by chrchang** [comment]
The plink2-users Google group (https://groups.google.com/g/plink2-users ) is a more appropriate place for this type of question.
