### ISSUE TITLE
What's the detailed model of  Cochran-Armitage trend test?

### ISSUE THREAD

**Issue by ddzhang3** [chrchang/plink-ng#165]
Dear professor, I'm wondering what's the mathematic detail of the trend test in plink. While the Cochran-Armitage trend test is always applied in R*2 contingency table, and in the genetic situation genotype data is usually used, yet the plink's trend test seems do test with allele count data as indicated in the AFF and UNAFF columns. So I'm a bit confused, could you please clarify it? Thanks

**Comment by chrchang** [comment]
Please use the plink2-users Google group for questions like this which don't involve a possible code change.
