### ISSUE TITLE
FID column added with --update-ids not saved to .psam unless explicitly requested

### ISSUE THREAD

**Issue by robkar** [chrchang/plink-ng#166]
Hello, I was confused for a while by this, so thought I'd report it:

I was loading an IID-only vcf in plink2, then trying to add FID from an external file before saving to pgen format. The log file indicated that IDs had been updated, but they were not in the output. Forcing with psam-cols=+fid gave the output I expected. I uploaded a minimal example to https://gist.github.com/robkar/397a10bd6c50630181b7385fe9f8fa6d

Could the default "maybefid" be made to pick up on FID being filled by --update-ids?

**Comment by chrchang** [comment]
Thanks for reporting this bug; it should be fixed by d80a0ec.

**Comment by robkar** [comment]
Yes, the new version works for me. Thank you very much for the quick fix!
