### ISSUE TITLE
Src download.  Is it updated?

### ISSUE THREAD

**Issue by BJWiley233** [chrchang/plink-ng#167]
Hi I just downloaded and extracted version [a2.3](https://github.com/chrchang/plink-ng/releases/tag/v2.00a2.3)

and in the file `2.0/libdeflate/lib/lib_common.h` it still has on line 15 `#include "common_defs.h"` instead of `#include "../common/common_defs.h"` that was committed in [September](https://github.com/chrchang/plink-ng/commit/0d1d854a76ad58cbadd6b55b157ec0d1a56e582f#diff-1085509189f0866836ae050453dd017c48b4524c1e69b7817712d0943a404d9c)

Should I just clone from github?

**Comment by BJWiley233** [comment]
Also https://github.com/chrchang/plink-ng/tree/master/2.0/libdeflate/libdeflate.h got moved and should be in the `libdeflate/lib` folder with all the other headers for libdeflate.

**Comment by chrchang** [comment]
Correct, the a2.3 tag corresponds to a year-old build.  (I plan to create another tag within the next month, after some merge functionality has been added.)

**Comment by chrchang** [comment]
libdeflate.h is still in the top-level directory, rather than lib/, in https://github.com/ebiggers/libdeflate .
