### ISSUE TITLE
Sample ID filtering in Plink2.0 still requires FID

### ISSUE THREAD

**Issue by rma47** [chrchang/plink-ng#168]
Hi Chris,

The Plink2.0 manual says that only a sample ID is needed to filter samples but --remove requires a FID in the text file to work.  

I tried to filter with only a IID in the text file and no filtering occurred, then I tried to filter with a FID and IID in the text file and then filtering occurred (all files otherwise the same).

Regards,
Rachel

IID without FID
PLINK v2.00a2.3LM AVX2 Intel (24 Jan 2020)     www.cog-genomics.org/plink/2.0/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /mnt/v/8_lowf/combined_min005_exld_exo.log.
Options in effect:
  --bfile /mnt/v/8_lowf/combined_min005_exld
  --make-bed
  --out /mnt/v/8_lowf/combined_min005_exld_exo
  --remove ./remove_outliers_list.txt

Start time: Thu Feb 11 10:39:03 2021
8080 MiB RAM detected; reserving 4040 MiB for main workspace.
Using up to 8 compute threads.
2892 samples (0 females, 0 males, 2892 ambiguous; 2892 founders) loaded from
/mnt/v/8_lowf/combined_min005_exld.fam.
1043755 variants loaded from /mnt/v/8_lowf/combined_min005_exld.bim.
Note: No phenotype data present.
--remove: 2892 samples remaining.
2892 samples (0 females, 0 males, 2892 ambiguous; 2892 founders) remaining
after main filters.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.fam ... done.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.bim ... done.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.bed ... done.

With FID and IID
PLINK v2.00a2.3LM AVX2 Intel (24 Jan 2020)     www.cog-genomics.org/plink/2.0/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /mnt/v/8_lowf/combined_min005_exld_exo.log.
Options in effect:
  --bfile /mnt/v/8_lowf/combined_min005_exld
  --make-bed
  --out /mnt/v/8_lowf/combined_min005_exld_exo
  --remove ./remove_outliers_list.txt

Start time: Thu Feb 11 10:56:58 2021
8080 MiB RAM detected; reserving 4040 MiB for main workspace.
Using up to 8 compute threads.
2892 samples (0 females, 0 males, 2892 ambiguous; 2892 founders) loaded from
/mnt/v/8_lowf/combined_min005_exld.fam.
84544 variants loaded from /mnt/v/8_lowf/combined_min005_exld.bim.
Note: No phenotype data present.
--remove: 2845 samples remaining.
**2845 samples** (0 females, 0 males, 2845 ambiguous; 2845 founders) remaining
after main filters.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.fam ... done.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.bim ... done.
Writing /mnt/v/8_lowf/combined_min005_exld_exo.bed ... done.
End time: Thu Feb 11 10:57:00 2021

**Comment by chrchang** [comment]
You can only omit the FID if your .fam file doesn't have FIDs (i.e. all the FIDs are 0).

**Comment by rma47** [comment]
Hi Chris,

Can I suggest that the manual is updated to reflect this?

The manual says any format is fine and that PLINK will cope.

[cid:image003.png@01D70097.53ACE360]

The manual could have the statement added that “when FIDs are assigned in PLINK, the text file needs to include the FID I.e. a file with a header of #IID only will not work”.

Regards,
Rachel Ainsworth

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chrchang** [comment]
The online documentation already explicitly states that "when FID is undefined, it is treated as '0'", with a link to a more complete discussion of how sample IDs work in plink2.
