### ISSUE TITLE
config.h required for compilation but not generated by Makefile.std

### ISSUE THREAD

**Issue by jrandall** [chrchang/plink-ng#17]
There seems to be new functionality (since 1.90b2k) that compiles Rconnections.cc which appears to require a `config.h` file (I presume this is of the type generated by autoconf's ./configure). However, the source tree doesn't include any autoconf files. 

How are we meant to generate an appropriate `config.h`?

**Comment by chrchang** [comment]
config.h has been added; sorry about the omission.
