### ISSUE TITLE
plink2 --keep not extracting everyone in the .txt file

### ISSUE THREAD

**Issue by LindsayMMB** [chrchang/plink-ng#172]
Hi,

I'm trying to only keep a subset of individuals so I created a .txt file with the FID and IID. I want to extract these people from my bfile. The .fam file has all of the same individuals(N=548) as my .txt file -exact same number and exact same IDs. But when I run the command, only N=336 individuals are kept.

Both plink and plink2 are doing this. Why?

**Comment by chrchang** [comment]
Since this is >99.9% likely to be a usage mistake rather than a bug report, the plink2-users Google group is the appropriate place to continue this discussion.  Include a .log file and your .fam and .txt files so I can explain what's going on.

**Comment by Nuvolar** [comment]
i'm also have this matter, then i found that the sample with "-" in the FID&IID treat as 0 both plink2&1.9. I don't whether it is a bug.
