### ISSUE TITLE
ERROR while vcf to plink

### ISSUE THREAD

**Issue by sekhwal** [chrchang/plink-ng#173]
I have a merged vcf file. Now, I am trying to use PLINK with following command. I tried to run this command in different ways at Window and Linux but it is showing following error. This command should generate .map and .ped files.

$plink --file merged-try --recode --out data
OR
$plink --file merged-try.vcf --out data

ERROR: Window
ERROR: No file [ merged-try.ped ] exists.

ERROR: Linux
Error: Failed to open merged-try.map

**Comment by chrchang** [comment]
Please post basic usage questions in the plink2-users Google group.
