### ISSUE TITLE
Inconsistent Fst values depending on the naming of populations

### ISSUE THREAD

**Issue by melodysyue** [chrchang/plink-ng#174]
Hello,

I am trying to calculate per-SNP Fst between two populations using Plink 1.9. However, I got very different fst values depending on how I named the populations. 

In the first example (lwf.pop.2*), I set population names as EKRP and IGPT, then calculated Fst 
plink2 --bfile lwf.pop.2 --chr-set 40 no-xy --fst --family --out lwf.pop.2

In the second example (lwf.rep.2*), I set the population names as GMZ4 and GMZ5, then calculated Fst
plink2 --bfile lwf.rep.2 --chr-set 40 no-xy --fst --family --out lwf.rep.2

I compared the generated Fst files and found out they were very different. I don't understand why simply changing the name of populations would change the Fst values. Could you help me with it? Thanks you!

[lwf_plink.zip](https://github.com/chrchang/plink-ng/files/6087245/lwf_plink.zip)

**Comment by chrchang** [comment]
Your lwf.pop.2 and lwf.rep.2 datasets don't have matching genotype data.  This can already be seen in the second variant (53:114:+).
