### ISSUE TITLE
Why alleles of ref ALT convert to "." on output vcf file? 

### ISSUE THREAD

**Issue by awakumaya** [chrchang/plink-ng#177]
Hi, I tried to convert the format of genotyping output file: .ped to .vcf. I found some variant information contain "." on the ALT column. Why were these alleles judged to deletion? In original ped file, there is variant information that does not contain '0' and converted to '.' in vcf.

**Comment by chrchang** [comment]
This type of usage question should be asked in the plink2-users Google group.
