### ISSUE TITLE
plink1.9 swaps some alternative and reference alleles when reading individual-major bed

### ISSUE THREAD

**Issue by dkolobok** [chrchang/plink-ng#178]
version
PLINK v1.90b3.30 64-bit (27 Jan 2016)

The command I'm running is plink19 --bfile tmp --make-bed --out output
Input files:
cat tmp.bim:
1       .       0       10177   AC      A
1       .       0       10235   TA      T
1       rs145072688     0       10352   TA      T
1       .       0       10539   A       C
1       rs376342519     0       10616   C       CCGCCGTTGCAAAGGCGCGCCG
1       .       0       10642   A       G
1       .       0       11008   G       C
1       .       0       11012   G       C
1       .       0       11063   G       T

cat tmp.fam:
0       vcf1    0       0       0       -9
0       vcf2    0       0       0       -9
0       vcf3    0       0       0       -9

hexdump -x tmp.bed
0000000    1b6c    fe00    03fc    fcec    fe03    03fc
000000c

Output file (see some ref/alt alleles are swapped):
cat output.bim
1       .       0       10177   A       AC
1       .       0       10235   TA      T
1       rs145072688     0       10352   TA      T
1       .       0       10539   A       C
1       rs376342519     0       10616   CCGCCGTTGCAAAGGCGCGCCG  C
1       .       0       10642   A       G
1       .       0       11008   G       C
1       .       0       11012   G       C
1       .       0       11063   G       T

When I use plink2 everything is fine

**Comment by chrchang** [comment]
See the --keep-allele-order documentation: https://www.cog-genomics.org/plink/1.9/data#ax_allele
