### ISSUE TITLE
--remove not working when individuals are duplicate

### ISSUE THREAD

**Issue by catlisboa** [chrchang/plink-ng#179]
--remove flag is not working to remove any individuals and I get the following error:

```
PLINK v1.90b6.10 64-bit (17 Jun 2019)          www.cog-genomics.org/plink/1.9/
(C) 2005-2019 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to chip_good_qual_check_sex_nohet.log.
Options in effect:
  --bfile chip_good_qual_check_sex
  --make-bed
  --out chip_good_qual_check_sex_nohet
  --remove-fam fail-het-qc.txt

257854 MB RAM detected; reserving 128927 MB for main workspace.
476559 variants loaded from .bim file.
1084 people (441 males, 639 females, 4 ambiguous) loaded from .fam.
Ambiguous sex IDs written to
chip_good_qual_check_sex_nohet.nosex
.
1084 phenotype values loaded from .fam.
Error: Duplicate ID '800 1152'. 
```

command ran: `plink --bfile chip_good_qual_check_sex --remove-fam fail-het-qc.txt --make-bed --out chip_good_qual_check_sex_nohet`

I know this is a duplicate ID in my fam file but I already tried to remove the duplicate individuals with this same flag and it's still not working.

Is there any workaround for this?

**Comment by chrchang** [comment]
You need to edit this .fam file outside of plink.
