### ISSUE TITLE
Fasta validation rejects common reference file (human_g1k_v37)

### ISSUE THREAD

**Issue by robkar** [chrchang/plink-ng#180]
I was trying to set reference alleles in my data with --fa and --ref-from-fa, but got an error message when using the latest plink2 (23 May 2021) and ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz (uncompressed): "Error: Unexpected character at beginning of line 51594898 of --fa file."

Line 51594898 turns out to be a blank line after the MT sequence, and before all the GL... contigs, and is the only blank line in the fasta file. An older plink2 version (12 Sep 2018) accepted the same fasta file, and [this looks like the relevant change](https://github.com/chrchang/plink-ng/commit/dd3b9cf062af8a71f45eda80474d1b61ad5e7427#diff-ffa222dd1116645bf4e787f61c774784d6c15b15f62a2727b1dd98e191e80a3bL552).

Removing the blank line from the fasta file got it to load in the current version, so I guess one could argue that this is a bug in the data, and not in plink2. On the other hand this reference is in wide use, so letting plink2 accept it unaltered would prevent some confusion I think.

As always, thanks for all your great work on plink2!

**Comment by chrchang** [comment]
Thanks for reporting this; it should be addressed by ab96a0f .

**Comment by chrchang** [comment]
(There is also a gzip-handling update that should allow the original .gz file to be usable.)

**Comment by robkar** [comment]
Wonderful, thanks!
