### ISSUE TITLE
plink v1-9: --chr-set limited to 95, suggest to remove this limit

### ISSUE THREAD

**Issue by richelbilderbeek** [chrchang/plink-ng#182]
When I run PLINK v1.9 to detect an association on the supplied toy data ([toy.ped](https://github.com/chrchang/plink-ng/blob/master/1.9/toy.ped) and [toy.map](https://github.com/chrchang/plink-ng/blob/master/1.9/toy.map)), this works perfectly for 95 chromosomes:

```
./plink --assoc --file toy --chr-set 95
```

with output:

```
ichel@N141CU:~/.local/share/plinkr/bug_report_v1_9$ ./plink --assoc --file toy --chr-set 95
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink.log.
Options in effect:
  --assoc
  --chr-set 95
  --file toy

7652 MB RAM detected; reserving 3826 MB for main workspace.
.ped scan complete (for binary autoconversion).
Performing single-pass .bed write (2 variants, 2 samples).
--file: plink-temporary.bed + plink-temporary.bim + plink-temporary.fam
written.
2 variants loaded from .bim file.
2 samples (2 males, 0 females) loaded from .fam.
2 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 2 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.75.
2 variants and 2 samples pass filters and QC.
Among remaining phenotypes, 1 is a case and 1 is a control.
Writing C/C --assoc report to plink.assoc ... done.
```

However, when I run

```
./plink --assoc --file toy --chr-set 96
```

I get:

```
richel@N141CU:~/.local/share/plinkr/bug_report_v1_9$ ./plink --assoc --file toy --chr-set 96
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink.log.
Options in effect:
  --assoc
  --chr-set 96
  --file toy

Error: Invalid --chr-set parameter '96'.
For more information, try "plink --help <flag name>" or "plink --help | more".
```

I expected PLINK v1.9 to work on 96 chromosomes as well. Or more precise: I expect no limit on the amount of chromosomes I can set (sure, memory problems due to this are mine :-) ). 

I suggest to remove this upper bound of 95 chromosomes, if possible.

I would enjoy this, as (1) this is useful when using simulating data  (2) [there are dipoloid species with more than 96 chromosomes](https://en.wikipedia.org/wiki/List_of_organisms_by_chromosome_count).

Thanks and cheers, Richel

**Comment by richelbilderbeek** [comment]
I close this Issue for now, I have gotten unsure if this is a valid report.

**Comment by chrchang** [comment]
This issue is discussed in the [--chr-set documentation](https://www.cog-genomics.org/plink/1.9/input#chr_set).

**Comment by richelbilderbeek** [comment]
Blimey, awesome job @chrchang! Also kudos for checking on on a closed Issue. In normal life, I'd buy you a couple of beers for that!
