### ISSUE TITLE
Error: Invalid bp coordinate on line 22 of .map file.

### ISSUE THREAD

**Issue by cks2903** [chrchang/plink-ng#183]
I have a problem with positions > 2Gbp in my .map file.
For every marker with a position> 2Gbp I get the following error when trying to do anything involving the .map file:

Error: Invalid bp coordinate on line 22 of .map file.
Error: Invalid bp coordinate on line 25 of .map file. etc.

If I manually make the value smaller, the problem does not occur.

Is there an explanation for this behaviour and how do I get around it?

I have attached the map file and log file in text formats.

[LDscore_chr1_20210616.txt](https://github.com/chrchang/plink-ng/files/6662844/LDscore_chr1_20210616.txt)

[genotypesFiltered_MAC10Imputed_ChrMapped_20210616.txt](https://github.com/chrchang/plink-ng/files/6662840/genotypesFiltered_MAC10Imputed_ChrMapped_20210616.txt)

**Comment by chrchang** [comment]
plink only supports 32-bit-integer coordinates, sorry.  You'll need to e.g. split the long chromosome(s) into pieces of length 2 billion in order to work with this data.
