### ISSUE TITLE
plink2: Error: Unrecognized flaf (--pmerge-list)

### ISSUE THREAD

**Issue by zillurbmb51** [chrchang/plink-ng#184]
Hi, I was trying to merge a list of pgen files using plink2 (PLINK v2.00a2.3LM 64-bit Intel (24 Jan 2020)). 
`plink2 --pfile my-pfile --pmerge-list list-merge.txt --make-pgen --out my-merged`
I was getting the above mentioned error. 

Interestingly I have another version "(PLINK v2.00a3LM 64-bit Intel (3 Feb 2021))" which has --pmerge-list flag enabled. It also produced the merged ouput but showing error: "Error: --pmerge[-list] concatenation is under development." Is it ok to use this version of plink2 to merge list of pgen files?
[chr1.step10.imputed.merged.log](https://github.com/chrchang/plink-ng/files/6701556/chr1.step10.imputed.merged.log)

**Comment by chrchang** [comment]
[--pmerge-list](https://www.cog-genomics.org/plink/2.0/#recent)'s first appearance in the version history is on 28 Feb 2021.
