### ISSUE TITLE
error making .bed file using plink

### ISSUE THREAD

**Issue by sekhwal** [chrchang/plink-ng#185]
Hi,
I have hapmap file (.hmp.txt). I am looking to create binary file of this file. Therefore I am using following command but plink shows the following error. please advise.

$plink2 --file se.hmp.txt --make-bed --out se

error:
Error: Unrecognized flag ('--file').

When I try on linux the plink shows following error:
Error: Failed to open (file_name.hmp.map)

**Comment by chrchang** [comment]
Please post basic usage questions on the [plink2-users Google group](https://groups.google.com/g/plink2-users), not here.
