### ISSUE TITLE
"--cnv-freq-exclude-above" works the same with "--cnv-freq-include-exact"

### ISSUE THREAD

**Issue by QidiFeng** [chrchang/plink-ng#189]
Hi Plink team,

I found that the command "--cnv-freq-exclude-above" gives exactly the same results as the command "--cnv-freq-include-exact" for cnv analysis. I used plink1.07. The toy data is attached below as all_cohorts.1.Kahn*. I produced two outputs all_cohorts.2.Kahn* and all_cohorts.3.Kahn* with commands listed in log files. 

Besides that, when I tried the same commands with plink1.9 or plink2. It reported "Error: Unrecognized flag ('--cfile')."

Best regards,
Qidi
[Example.tar.gz](https://github.com/chrchang/plink-ng/files/6896023/Example.tar.gz)

**Comment by chrchang** [comment]
Sorry, but as you noted, plink's CNV module has not been implemented in v1.9 or v2.0, and it's not a high priority since it's disconnected from the rest of the program and almost never used.  I recommend using other software to perform this analysis.
