### ISSUE TITLE
failed to open bed file

### ISSUE THREAD

**Issue by ketkijoshi278** [chrchang/plink-ng#191]
Hello,
I am trying plink software to convert bed file to vcf file. But I am getting error.
The command:
plink  --bfile [hglft_genome_470a4_43f4c0.bed] --recode vcf --out [outfile.vcf]

The error:
PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to i.log.
Options in effect:
  --bfile [hglft_genome_470a4_43f4c0.bed]
  --out i
  --recode vcf

191830 MB RAM detected; reserving 95915 MB for main workspace.
Error: Failed to open [hglft_genome_470a4_43f4c0.bed].bed.
(TWAS) c506-003[skx](1051)$ plink  --bfile [hglft_genome_470a4_43f4c0] --recode vcf --out [outfile.vcf]
PLINK v1.90b6.21 64-bit (19 Oct 2020)          www.cog-genomics.org/plink/1.9/
(C) 2005-2020 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to i.log.
Options in effect:
  --bfile [hglft_genome_470a4_43f4c0]
  --out i
  --recode vcf

191830 MB RAM detected; reserving 95915 MB for main workspace.
Error: Failed to open [hglft_genome_470a4_43f4c0].bed.

This is the content of my .bed file for reference:
chr22   15927338        15927339
chr22   15926767        15926768
chr22   15925769        15925770
chr22   15924807        15924808
chr22   15924146        15924147
chr22   15923295        15923296
chr22   15922887        15922888
chr22   15922875        15922876
chr22   15922837        15922838
chr22   15922096        15922097
chr22   15921734        15921735
chr22   15920797        15920798
chr22   15918255        15918256
chr22   15917692        15917693
chr22   15917389        15917390
chr22   15917224        15917225
chr22   15917199        15917200
chr22   15916940        15916941
chr22   15916940        15916941
chr22   15916817        15916818
chr22   15916706        15916707
chr22   15916309        15916310
chr22   15915686        15915687
chr22   15915652        15915653
chr22   15914587        15914588
chr22   15912242        15912243
chr22   15912242        15912243
chr22   15908475        15908476
chr22   15905975        15905976
chr22   15905929        15905930

**Comment by chrchang** [comment]
Basic usage/troubleshooting questions should be posted to the [plink2-users Google group](https://groups.google.com/g/plink2-users), not here.

**Comment by zhangjia12345** [comment]
I know the answer. you can try to change code""D:/g1000_eur" to ""D:/g1000_eur/g1000_eur" in R. It means that adds addtionally "//g1000_eur". Have a try!
