### ISSUE TITLE
splitting by chromosomes produce different number of samples in each chromosome

### ISSUE THREAD

**Issue by zillurbmb51** [chrchang/plink-ng#192]
Hi,

I was using a for loop to split a plink file into chromosomes. 
```
BFILE=<my_bfile>
for i in $(seq 22); do plink --silent --bfile ${BFILE} --chr $i --out ${BFILE}.chr$i; done
```
It is not giving me the same sample size (number of lines in fam file of each output chromosome). How is it possible?
How could I fix it?

I also tried `plink --bfile "${input_prefix}.filtered" --chr "${3}" --out "${chrom}" --make-bed`
to give input from command line to avoid for loop. But still getting getting different number of samples in each outputted chromosome. 

Any help?

**Comment by chrchang** [comment]
Please post full .log files from these runs, and preferably the original .fam file and two differing output .fam files.

**Comment by zillurbmb51** [comment]
Thanks. Here they are. As there are multiple files, for convenience they were zipped.
[logs_fams_batch2.zip](https://github.com/chrchang/plink-ng/files/7205045/logs_fams_batch2.zip)

**Comment by chrchang** [comment]
The working directory is not the same in these .logs, yet the --bfile argument always refers to the current working directory.  So it appears very likely that you are not using the same *input* fileset across these runs; they probably diverged at some earlier step.

**Comment by zillurbmb51** [comment]
The working directory is same. I am using nextflow (https://www.nextflow.io/). It creates a temporary directory for each chromosome but use the same input creating symbolic link and finally gives output to the current working directory. There is no way of using different input because I have only one bfile with this name.

**Comment by chrchang** [comment]
Can't provide any further help here, the .logs make it clear that the input is different in your runs.

**Comment by zillurbmb51** [comment]
Ok. I have implemented the same command locally (slurm) without using nextflow. But the same issue persists. Here is the new logs and fams.
[logs_and_fams_test1.zip](https://github.com/chrchang/plink-ng/files/7208872/logs_and_fams_test1.zip)

**Comment by chrchang** [comment]
Again, the logs show that this is an issue with how the cluster infrastructure is being used, not with plink.

**Comment by chrchang** [comment]
Incidentally, if you use plink 2.0 instead of 1.9 for this operation, you'll get a more informative error message than "File read failure" when something goes wrong with the cluster filesystem.
