### ISSUE TITLE
Plans to get pgenlibr on CRAN?

### ISSUE THREAD

**Issue by richelbilderbeek** [chrchang/plink-ng#193]
Dear @chrchang,

I was happy to find the `pgenlibr` R package to read `.pgen` files and I intend to use it in one of my packages.

The problem is that I intend to get my package on CRAN, where CRAN packages are only allowed to depend on CRAN packages.

Are there plans to get the `pgenlibr` R package on CRAN?

I would be open to help in a way, e.g. by adopting it in my package, but a standalone `pgenlibr` R package feels preferred to me, especially as -as far as I understand- the .pgen file format is not cast in stone yet.

Thanks for your reply and cheers, Richel Bilderbeek

**Comment by chrchang** [comment]
Yes, there's technically one part of the .pgen format that has not been fleshed out yet (multiallelic dosages), but that part is unimportant for most applications.  I will work on it this weekend.

**Comment by richelbilderbeek** [comment]
@chrchang that would be amazing! Thanks so much!

**Comment by chrchang** [comment]
Ended up being delayed by far more than a weekend, but pgenlibr is now on CRAN.
