### ISSUE TITLE
recommended use in C++ project

### ISSUE THREAD

**Issue by jvanalstine** [chrchang/plink-ng#198]
Hi Chris,

How do you recommend using plink2 as a library? Is it typically best to just vendor it within my project, or is there a library make target that i'm missing?

**Comment by chrchang** [comment]
Hmm, it's probably about time that I add make target(s) for a few likely use cases.  Are you only using code other include/ and other subdirectories?

**Comment by chrchang** [comment]
The Makefile under build_dynamic/ now has pgenlib.a and plink2lib.a build targets.

**Comment by jvanalstine** [comment]
Perfect, thank you!
