### ISSUE TITLE
strange artifacts seen with --r2

### ISSUE THREAD

**Issue by nvictus** [chrchang/plink-ng#20]
I've been generating large maps of kb-aggregated pairwise LD r^2 values from the 1000 genomes project. The new implementation in plink-1.9 is blazingly fast :), but I keep getting a strange "doubling" distortion effect in the lower half of the matrix. It extent of the effect is different in `--bin` and `--bin4` mode, and I saw it in `--gz` mode as well. I get the right result using the text dump LD matrix from plink-1.07. I've put together a repo that reproduces the problem:

https://github.com/nezar-compbio/plink2-bug

**Comment by chrchang** [comment]
I've replicated this low-memory bug; will try to post a fix today.

**Comment by chrchang** [comment]
Should be fixed in the February 10 builds; let me know if you still have any problems.

**Comment by nvictus** [comment]
Fantastic! It's working with the Feb 10 build. Thanks for the quick response :)
I'll let you know if I encounter anything else.
