### ISSUE TITLE
Heterozygous haploid errors

### ISSUE THREAD

**Issue by klmartinez** [chrchang/plink-ng#200]
I have a large dataset whose autosomes I was able to successfully phase and impute using TOPMed. I have tried doing the same with the X chromosome but keep running into issues.

Before trying to impute with TOPMed, I did per-individual QC and per-marker QC, then ran checkVCF, and corrected any issues identified with checkVCF such as fixing allele flips, removing duplicate sites, etc. – I performed this on the complete dataset including the X chromosome.

However, when trying to impute the X chromosome it doesn’t get past TOPMed Quality Control. I did find an old post on [Biostars ](https://www.biostars.org/p/247101/) about someone having issues with their X chromosome when using the Michigan imputation server.

They specifically got an error that there were heterozygous variants in their males. Thus, it was suggested that they correct for these heterozygous haploid errors using the following PLINK command:

`plink --bfile Input_data --set-hh-missing --recode vcf --out Result_filename`

However, I am concerned because when I use PLINK's `--sample-counts`, I see that all my individuals are assigned an "ambiguous" sex even though I know I have both male and female individuals. **So does this mean I am losing heterozygous variant information on my female individuals? Is '--set-hh-missing' the correct approach?**

I could potentially go back and re-encode the sex information into the PLINK files and then use `--set-hh-missing` , but I am worried since I will have to recode that as a VCF in order for it to be used in TOPMed, the sex info will not be retained, thus leading to the same error because people will read as having heterozygous haploid errors. 

**Am I misunderstanding PLINK's `--set-hh-missing`? Is there a alternative approach I can take?**

**Comment by chrchang** [comment]
Please post general usage questions to the [plink2-users Google group](https://groups.google.com/g/plink2-users), not here.
