### ISSUE TITLE
Error: Failed to extract eigenvector(s) from GRM.

### ISSUE THREAD

**Issue by ManuelMoradiellos** [chrchang/plink-ng#201]
Hi~!

I wanted to use  Plink (v1.90b6.21 on Ubuntu  20.04.1 Linux x86_64) to obtain a Population Stratification PCA
of my variants dataset.  

This dataset is a .tsv that I've tried to turn into a mock-up .vcf as input for plink, the .vcf headers are not exactly 
real and I omitted including some information on various columns (QUAL, INFO) as they were a bit cumbersome
to add and as I thought that the Genotype (GT) information should be enough for my task.

I don't know if I'm missing something in the input .vcf or if I'm overlooking a command as I'm relatively new to 
bioinformatics, but I include the .log and a fraction of the input .vcf if its any help.
Thanks in advance!!

[gazpacho.log](https://github.com/chrchang/plink-ng/files/7529070/gazpacho.log)
[plink_test_input.vcf.gz](https://github.com/chrchang/plink-ng/files/7529082/plink_test_input.vcf.gz)

**Comment by chrchang** [comment]
>99.5% of the genotypes in your input VCF are missing.  PCA should not be used on variants with more than ~10% missing data.

**Comment by ManuelMoradiellos** [comment]
Thanks, that was it!  Here I was using a small subset as a toy example, but once I tried to apply it to my whole dataset I got what I asked for.

**Comment by tanwei123456** [comment]
[all.vcf.gz](https://github.com/chrchang/plink-ng/files/8763692/all.vcf.gz)
Sorry to bother you, but I came across the same mistake：Failed to extract eigenvector(s) from GRM. I include the input .vcf if its any help.
Thank you very much!

**Comment by chrchang** [comment]
Rerun --pca with plink 2.0; it will provide a more useful error message.

**Comment by tanwei123456** [comment]
Thank you for your reply. After I deleted several samples with very high similarity with reference genes, the problem was solved
