### ISSUE TITLE
pgen spec: when bottom 3 bits of the record type is 3 

### ISSUE THREAD

**Issue by kose-y** [chrchang/plink-ng#205]
The current PGEN spec states:

3: LD-compressed, inverted. A difflist with all (sample ID, genotype value) pairs for samples in different categories than they would be in the previous non-LD-compressed variant after inversion (categories 0 and 2 swapped). This addresses spots where the reference genome is “wrong” for the population of interest.

I'm working on an independent PGEN reader in Julia, and it seems that the genotype value in the difflist is also inverted. I think it should be explicitly stated in the spec.

**Comment by chrchang** [comment]
Thanks for reporting this; it should be clarified by f004302 .

**Comment by kose-y** [comment]
Thanks!
