### ISSUE TITLE
id-paste=iid option for --export A-transpose

### ISSUE THREAD

**Issue by dylkot** [chrchang/plink-ng#209]
Hi there,

Thank you for maintaining and actively developing this incredibly useful tool!

I am trying to export a Plink2 file to a traw that I can use with the GMMAT package to run mixed models logistic regression. I am using a command like

```
plink2 --export A-transpose --pfile pgenbase --keep samples_noFID.txt --keep-allele-order --maf 1e-2 --hwe 1e-12 --geno 5e-2 --out outbase --set-all-var-ids @:#[b37]\$r,\$a
```

However, this creates output files where samples have a 0_ in their name like so

```
0_WG0284565-DNA_A08_G-7030   0_WG0284565-DNA_A09_G-7022   0_WG0284565-DNA_B08_G-7260 
```

Is there any way to avoid this behavior and just output the IID as the sample name in the header? The id-paste=iid flag doesn't seem to be available for the --export A-transpose option.

Thanks so much!

**Comment by chrchang** [comment]
Unfortunately, A-transpose is an older format and this would violate the specification, so this won't be built into plink2.

**Comment by dylkot** [comment]
OK, thanks for letting me know. I'll try to get by with VCF files. It would essentially be the same if I could get it to just output the dosage value (DS) and not GT:DS. Is there any way for it to do that? Even with
```--export vcf vcf-dosage=DS-force```
it seems to output both GT and DS.

**Comment by chrchang** [comment]
Ok, I will look into adding a DS-only mode soon.

**Comment by chrchang** [comment]
DS-only is now implemented.
