### ISSUE TITLE
 --vcf-idspace-to _  and Error: Multiple instances of '_' in sample ID.

### ISSUE THREAD

**Issue by ryanlayer** [chrchang/plink-ng#21]
I am not sure how to get around this issue.   

    time ./plink --make-bed --vcf foo.vcf.gz --out foo.vcf.gz.plink --allow-extra-chr --vcf-idspace-to _
    PLINK v1.90b3d 64-bit (10 Feb 2015)        https://www.cog-genomics.org/plink2
    (C) 2005-2015 Shaun Purcell, Christopher Chang   GNU General Public License v3
    Logging to foo.vcf.gz.plink.log.
    129004 MB RAM detected; reserving 64502 MB for main workspace.
    Error: Multiple instances of '_' in sample ID.

**Comment by chrchang** [comment]
"--const-fid 0" is probably the simplest way way; it causes all family IDs to be set to "0", and individual IDs to be set to the ID in the VCF file.

I will modify the error message to suggest --const-fid as a workaround.
