### ISSUE TITLE
covariates in plink

### ISSUE THREAD

**Issue by mfazel** [chrchang/plink-ng#210]
Hi,

This is more of a question than issue but I could not find a clear answer to it. When we use --covar flag, in the association results there are "ADD" aditive effect ("DOMDEV" if I used --genotypic as dominant deviation from additive effect) and all other "COV" variables effect that are used in the model. What I got from documentation was that "GENO_2DF" is the additive/dominant model adjusted for covariates. My question: Is "ADD" row in this file, already adjusted for covariates introduced by covar file or how can one calculate adjusted additive effect for covariates?

Thanks,
Mehdi

**Comment by chrchang** [comment]
- The plink2-users Google group is a better place to ask (and search for answers to) usage questions.
- The GENO_2DF row contains a joint-test p-value.  The ADD row is adjusted for covariates.

**Comment by mfazel** [comment]
Thanks a bunch for clarification. Made it easier!
