### ISSUE TITLE
plink1.9 --23file, chromosoem out of order

### ISSUE THREAD

**Issue by GENEDECODERS** [chrchang/plink-ng#211]
My command like this:
 plink1.9 --23file /home/jiaxue/Downloads/ID3074.txt ID3075 3074 i -9 --out 3074txt
PLINK v1.90b6.16 64-bit (17 Feb 2020)          www.cog-genomics.org/plink/1.9/

I got the warning message like this:
31849 MB RAM detected; reserving 15924 MB for main workspace.
Error: Chromosomes in /home/jiaxue/Downloads/ID3074.txt are out of order.

My ID3074.txt file in such a format:

#rsid	 chromosome	 position	 genotype
.	1	156084877	CC
rs1060502211	1	156105743	GG
rs1064796677	1	156105833	CC
rs1064794269	1	17349122	CC
rs1060503759	1	17350508	CC

Is there anybody help me out with --23file format?

**Comment by chrchang** [comment]
Please ask usage questions in the plink2-users Google group (https://groups.google.com/g/plink2-users ), not here.
