### ISSUE TITLE
python setup.py incorrect path

### ISSUE THREAD

**Issue by KangchengHou** [chrchang/plink-ng#215]
Here I am reporting two incorrect path in setup.py (i was trying to install with `pip install -e .` at `2.0/Python`)
which is modified in commit https://github.com/chrchang/plink-ng/commit/16a462ea04abd38a59c8130034bc8dfb2246c8ab

1. `src/pgenlib/pgenlib.pyx` seems to be incorrect?
https://github.com/chrchang/plink-ng/blob/779a2a02b6ec2b5adba716a6e54bd31fba953986/2.0/Python/setup.py#L11
2. `README.md` should be `ReadMe.md`, or vice versa
https://github.com/chrchang/plink-ng/blob/779a2a02b6ec2b5adba716a6e54bd31fba953986/2.0/Python/setup.py#L23

As always, thanks for this great library

**Comment by chrchang** [comment]
Oops, I forgot to propagate part of this update; thanks for reporting this.  Let me know if you still have a problem with this after 67aaf03 .
