### ISSUE TITLE
[pgenlib] `phasepresent_out` buffer has too few columns in `read_alleles_and_phasepresent_list`

### ISSUE THREAD

**Issue by aryarm** [chrchang/plink-ng#216]
## Observed behavior

When I try to execute `read_alleles_and_phasepresent_list()` with a value of `phasepresent_out` with dimension exactly equal to the number of samples, I get an error:

```python
import numpy as np
from pgenlib import PgenReader
pgen = PgenReader(bytes("simple.pgen", "utf8"))
indices = np.array([1, 3], dtype=np.uint32)
data = np.empty((2, 10), dtype=np.int32)
phasing = np.zeros((2, 5), dtype=np.uint8)
pgen.read_alleles_and_phasepresent_list(indices, data, phasing)
```
> RuntimeError: Variant-major read_alleles_and_phasepresent_list() phasepresent_out buffer has too few columns (5; current sample subset has size 5, and column count should be twice that)

But when I use a value of `phasepresent_out` with dimension twice the number of samples, I observe that the last half of the filled `phasepresent_out` array is simply untouched.

```python
phasing = np.zeros((2, 10), dtype=np.uint8)
pgen.read_alleles_and_phasepresent_list(indices, data, phasing)
```
```
> phasing
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], dtype=uint8)
```

## Expected behavior
Shouldn't `phasepresent_out` have a dimension with length exactly equal to the number of samples, rather than twice the number of samples? I don't have to double the length of the `phasepresent_out` array when I run `read_alleles_and_phasepresent()`, for instance.

## Reproducible example
For the code referenced above, you can use [this pgen file](https://github.com/gymrek-lab/haptools/blob/c8a77737c5882856edad590cfedde38430f86fbe/tests/data/simple.pgen), which I created from [this VCF file](https://github.com/gymrek-lab/haptools/blob/c8a77737c5882856edad590cfedde38430f86fbe/tests/data/simple.vcf) using
```bash
plink2 --vcf simple.vcf --out simple
```

**Comment by chrchang** [comment]
`read_alleles_and_phasepresent()` handles a single variant.  `read_alleles_and_phasepresent_list()` handles a list of variants; the length of the second dimension of `phasepresent_out` should be the number of variants you are requesting.

**Comment by chrchang** [comment]
Ok, this was a bug; thanks for reporting this.  It should be fixed in 0df8e71 and today's PyPI version.

**Comment by aryarm** [comment]
great, thank you so much!

**Comment by aryarm** [comment]
@chrchang , any chance you can also upload a wheel?
