### ISSUE TITLE
Half-missing call in .ped file at variant 55, line 640.

### ISSUE THREAD

**Issue by Daluser1** [chrchang/plink-ng#219]
Dear Dr. Chang,

I am trying to create .bed file from .ped and .map using this line of code:

plink --file "/scratch/.../Variants/20220622_Plink"  --no-fid --no-parents --no-sex --no-pheno --aec --mind 0.1 --maf 0.05 --geno 0.1 --output-missing-genotype 0 --make-bed --out test

but, I am still getting an error that says : Half-missing call in .ped file at variant 55, line 640.

I checked line 55 of .ped file and there is "0 0" at the first column. I was wondering is there any way that I can solve this issue?

I appreciate your time and consideration.

Best Regards,
D

**Comment by chrchang** [comment]
Please post usage questions like this to the plink2-users Google group.
