### ISSUE TITLE
Error: REF allele on line 1071 of --pgen-diff .pvar file conflicts with loaded REF allele

### ISSUE THREAD

**Issue by hsmith9002** [chrchang/plink-ng#225]
Hi,

This is the full error message. 

"Error: REF allele on line 1071 of --pgen-diff .pvar file conflicts with loaded
REF allele, and neither are flagged as provisional."

Can you help me understand what is going wrong here. I wasn't able to find this error in your documentation. Here are the lines leading up to the error:

`./plink2 --vcf ${GTAK}.vcf.gz --double-id --make-pgen --sort-vars --out ${GTAK}`

`./plink2 --vcf ${DNANEXUS}_chr22.vcf.gz --double-id --make-pgen --sort-vars --out ${DNANEXUS}`

`./plink2 --pfile ${GTAK} --pgen-diff ${DNANEXUS} include-missing --out ${OUT}
`
The --make-pgen calls seem to working fine, but I get the error when running pgen-diff.

Thank you.

**Comment by chrchang** [comment]
Some REF/ALT alleles are swapped in at least one of your VCFs.

If you don't have any indels, the --ref-from-fa flag can be used to repair the problem VCF.  Otherwise, you need to debug something earlier in your pipeline.
