### ISSUE TITLE
plans to get pgenlib on bioconda?

### ISSUE THREAD

**Issue by aryarm** [chrchang/plink-ng#228]
Hi @chrchang ,

Our team really enjoys using the pgenlib python library in this repository. In fact, we like it so much that we've integrated it as a dependency in a toolkit that we're building. One component of our tool is a python library that can load VCFs and PGEN/PVAR/PSAM files into identical data structures.

We're nearing our initial release of this library, and we're considering publishing it to bioconda. ([It's already on PyPI](https://pypi.org/project/haptools/).) I understand that development of pgenlib is still underway, so I wanted to inquire about your plans to get the pgenlib python package on bioconda?

I would be happy to help with this in any way, if you feel like you're ready.

Thanks in advance for your reply and for developing such a useful resource for the community!

**Comment by chrchang** [comment]
Now available: https://anaconda.org/bioconda/pgenlib

**Comment by aryarm** [comment]
thank you!
