### ISSUE TITLE
Missing zlib

### ISSUE THREAD

**Issue by rnowling** [chrchang/plink-ng#23]
The Makefile appears to assume that the zlib library is located in the current directory

    g++ -Wall -O2 plink.c plink_assoc.c plink_calc.c plink_cluster.c plink_cnv.c plink_common.c plink_data.c plink_dosage.c plink_family.c plink_filter.c plink_glm.c plink_help.c plink_homozyg.c plink_lasso.c plink_ld.c plink_matrix.c plink_misc.c plink_rserve.c plink_set.c plink_stats.c SFMT.c dcdflib.c pigz.c yarn.c Rconnection.cc hfile.c bgzf.c -m32 -o plink -L/usr/lib64/atlas -llapack -lcblas -latlas -lm -lpthread -L. zlib-1.2.8/libz.so.1.2.8
    g++: error: zlib-1.2.8/libz.so.1.2.8: No such file or directory

It seems it might be better to use the system's zlib library.

**Comment by chrchang** [comment]
I plan to switch to system zlib when I'm no longer frequently updating the codebase.  For now, the likelihood that statically-linked zlib 1.2.8 will have higher performance than the system-installed version is too high.

The plink_first_compile script downloads zlib 1.2.8 into the current directory.

**Comment by rnowling** [comment]
Thanks for pointing out a workaround.

I don't quite understand your point about zlib -- can you elaborate?.  Is the issue that common platforms come with an older version (e.g., CentOS 7 comes with 1.2.7)?  I don't see how static vs dynamics linking would make a difference in performance.  If you need a statically-linked version, CentOS 7 has packages for both statically and dynamically linked versions of zlib -- maybe other platforms do as well?

**Comment by chrchang** [comment]
Yes, the issue is that plink is used on a bunch of systems with much older zlibs, and it is sometimes a pain for the users to get a newer version installed.

**Comment by rnowling** [comment]
Makes sense!  Thanks!
