### ISSUE TITLE
Specifying pairs for IBD estimation 

### ISSUE THREAD

**Issue by idubinkin** [chrchang/plink-ng#230]
Is there a way to calculate IBD only for specified pairs of individuals? For example, if I need to find relatives  for only one individual in a set of a million, can I avoid computing 1’000’000x1’000’000 matrix and instead calculate just 1x1’000’000? Could it be achieved via retired --genome-lists option?

**Comment by chrchang** [comment]
See plink 2.0's [--make-king-table command and --king-table-require flag](https://www.cog-genomics.org/plink/2.0/distance#make_king).

**Comment by idubinkin** [comment]
Thank you, i'll look into that.
