### ISSUE TITLE
--score with mean imputation calculates allele frequency for unneeded alleles

### ISSUE THREAD

**Issue by dvg-p4** [chrchang/plink-ng#237]
I'm currently trying to use plink2 to calculate PGSs, but noticing that it takes incredibly long to calculate allele frequencies unless I set the `no-mean-imputation` flag. Since the number of variants I have in my score file is very small, and my input pgen is very large, I presume that it must be calculating allele frequencies for every variant in my pgen file. (A glance at the source code seems to suggest this is the case, though I'm not 100% sure.)

**Comment by chrchang** [comment]
See https://www.cog-genomics.org/plink/2.0/input#read_freq .

**Comment by dvg-p4** [comment]
So this needs to be a two-step process?
