### ISSUE TITLE
Adding columns from VCF into plink result files

### ISSUE THREAD

**Issue by pengxiao78** [chrchang/plink-ng#238]
My VCF files have the following header,
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT ...

The plink.assoc.adjusted result file has the header as follows,
CHR SNP UNADJ GC BONF HOLM SIDAK_SS SIDAK_SD FDR_BH FDR_BY

The plink.assoc reult file has the the header as follows,
CHR SNP BP A1 F_A F_U A2 CHISQ P OR

How can I add REF and ALT columns from VCF into the plink.assoc (BP may be the POS) and  POS, REF and ALT from VCF into plink. assoc.ajusted?

Thanks!

**Comment by chrchang** [comment]
See plink 2.0 --glm (https://www.cog-genomics.org/plink/2.0/assoc#glm ), and how optional column sets work in plink 2.0 (https://www.cog-genomics.org/plink/2.0/general_usage#colset ).

(Meanwhile, your failure to include covariates in your analysis is almost certainly a mistake, and plink 2.0 --glm will tell you this.)
