### ISSUE TITLE
Any updates on https://www.cog-genomics.org/?

### ISSUE THREAD

**Issue by Klortho** [chrchang/plink-ng#24]
Sorry to create this issue here, but there are no "contact" links on the [cog-genomics.org](https://www.cog-genomics.org/) site.

I saw Steven Hsu's talk on this study over a year ago, and I'm very curious about it.  I notice that the main page of the site hasn't had any "news" items in over two years. How is it going?

If you could pass this message on to the right person, I'd appreciate it!

**Comment by chrchang** [comment]
You can send an email to contact@cog-genomics.org to ask about the study.
