### ISSUE TITLE
Document mapping of chromosomes to numeric codes with --output-chr 26

### ISSUE THREAD

**Issue by dvg-p4** [chrchang/plink-ng#240]
Empirically, it seems to be:

X -> 23
Y -> 24
XY, PAR1, PAR2 -> 25
M, MT -> 26

but it would be nice if this were documented at https://www.cog-genomics.org/plink/2.0/data#irreg_output and/or https://www.cog-genomics.org/plink/2.0/formats#pvar

**Comment by chrchang** [comment]
This is already mostly spelled out under the --chr documentation(https://www.cog-genomics.org/plink/2.0/filter#chr ) , but I will add an additional link from --output-chr, and add a note about PAR1/PAR2 using the XY output code under "--output-chr 26" or "--output-chr chr26".
