### ISSUE TITLE
Error: No entries in phenotype.txt correspond to loaded sample IDs.

### ISSUE THREAD

**Issue by vishalsnegi** [chrchang/plink-ng#242]
I am trying to add phenotype information from the `pheno_modified.txt` to plink files (`vcbcf_vcf_plink.pgen`, `vcbcf_vcf_plink.psam`, and `vcbcf_vcf_plink.pvar`).

The first fours sample ids in the `pheno_modified.txt` file looks as follows:
```
FID     IID     PHENO
AA01    AA01    1
AC01    AC01    1
AD01    AD01    1
AE01    AE01    3

```
The first four sample ids in `vcbcf_vcf_plink.psam` files look like this:
```
#IID    SEX
AA01    NA
AC01    NA
AD01    NA
AE01    NA
```

I used the following command:
`plink2 --pfile vcbcf_vcf_plink --pheno pheno_modified.txt --pheno-name PHENO --make-pgen --out vcbcf_vcf_pheno`

I am getting the following error:  No entries in pheno_modified.txt correspond to loaded sample IDs.

**Comment by chrchang** [comment]
Please ask basic usage questions in the [plink2-users Google group](https://groups.google.com/g/plink2-users).
