### ISSUE TITLE
Python API import errors with latest version

### ISSUE THREAD

**Issue by francois-a** [chrchang/plink-ng#243]
When installing from PyPI:
```
import pgenlib
ImportError: .../pgenlib.cpython-311-x86_64-linux-gnu.so: undefined symbol: zError
```

When compiling from the repository (following instructions in the README):
```
import pgenlib
ImportError: .../pgenlib.cpython-311-x86_64-linux-gnu.so: undefined symbol: inflate
```

Please let me know if you need additional details.

**Comment by chrchang** [comment]
You need to install zlib on your system.

**Comment by francois-a** [comment]
I should have mentioned that, it's installed.

**Comment by chrchang** [comment]
Ok, I've replicated this issue on a Linux test machine, will try to post a fix today.

**Comment by chrchang** [comment]
pgenlib 0.90.1 is posted; let me know if it doesn't solve the problem for you.

**Comment by francois-a** [comment]
Awesome! Thanks for the quick fix, it works now.
