### ISSUE TITLE
plink2 --sample-count running out of memory

### ISSUE THREAD

**Issue by janxkoci** [chrchang/plink-ng#250]
I'm trying a rather simple operation and I keep running out of memory, which is odd, because this should be very memory-friendly task (I know, because I [wrote a script](https://github.com/janxkoci/PopGen.awk/tree/main/scripts#vcfgtcountgawk) for similar purpose, but it runs orders of magnitude slower than `plink2`).

You can see the full log below, but a few things are worth noting:

- The BCF in question is very large - 180 GB. It contains only six human samples, but **all positions** (including invariant) from chromosomes 1-22 - that is **2881033286 sites**. Nevertheless, the resulting table should be 6 rows x ~10 columns IIRC and the accumulators for the summary stats should take negligible memory.
- The detected memory is for the whole compute node, while the job was submitted with 48 GB of RAM. In any case, `plink2` gives up after reaching around **16 GB of RAM usage**, no matter what I try.

plink2.log:

```
PLINK v2.00a3.3LM 64-bit Intel (3 Jun 2022)
Options in effect:
  --bcf href_archaics.bcf
  --memory 48000
  --sample-counts

Hostname: node1
Working directory: /home/users/koci/Human/admixr/david
Start time: Mon Nov  6 22:26:45 2023

Random number seed: 1699306005
191871 MiB RAM detected; reserving 48000 MiB for main workspace.
Using up to 80 threads (change this with --threads).

Error: Out of memory.  The --memory flag may be helpful.

End time: Mon Nov  6 22:48:05 2023
```

**Comment by chrchang** [comment]
- I'm pretty sure the error message is incorrect (I will take a look tomorrow), but I know that no PLINK version can handle this job as stated.  PLINK is limited to slightly under 2^31 variants.  You will need to split and/or filter that BCF to use it with PLINK, then aggregate results.
- The most recent --sample-counts bugfix was in January 2023, so I recommend updating your PLINK build.

**Comment by janxkoci** [comment]
> PLINK is limited to slightly under 2^31 variants.

This sounds like the crux of the problem. I'm trying to verify information in a bcf I made, before I move forward with an actual analysis (ARGweaver). I can't really filter the file, but I can probably split it and compare by parts. Maybe I can filter it too, if I do it smart enough.. 🤔 I need to think about my options..

But thanks for the pointer.

Also, can the resource detection be improved to reflect limits imposed by submission system? I didn't really have issues with it, but it can be confusing I guess.

**Comment by chrchang** [comment]
Don't know if it covers your use case, but there was a Linux resource-detection improvement in March 2023.

**Comment by janxkoci** [comment]
I've updated plink2 yesterday and tried to rerun the same task. The version is now reported as

```
PLINK v2.00a5LM 64-bit Intel (23 Sep 2023)
```

As expected, it still fails with the same error, but that's not really why I was trying it.

> there was a Linux resource-detection improvement in March 2023

I see some improvements - CPU threads are now correctly limited to specs provided by the job scheduler (Torque PBS in our case btw). Memory is still reported for the whole node, but it now shows "available" memory too, which I interpret as free memory not consumed by other jobs currently running at the node.

I now realize this detection may be quite scheduler-dependent, so FWIW we plan to move to Slurm at some point in the near future, as it seems to be generally better in every way (PBS is too quirky, no matter if Torque or Pro/OpenPBS). So if you want to focus on one scheduler at a time, I'd suggest to start with Slurm, it's probably gonna be the easiest to work with.

And I'm also gonna close this, as I don't really see any immediate action to be taken here.

**Comment by janxkoci** [comment]
Sorry to bump this, just wanted to record a **workaround** for others, including future me.

As you mention in your docs, this feature is a port from `bcftools stats`, which runs slower, but doesn't seem to have the same limitation on the number of sites. So anyone can use the following to obtain the same information:

```bash
BCF=input.bcf

bcftools stats -S <(bcftools query -l $BCF) $BCF | grep PSC # PSI for indels
```
