### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by danieller** [chrchang/plink-ng#255]
Hi, I am trying to install 'pgenlibr', however, I keep receiving the issue ERROR: compilation failed for package ‘pgenlibr'. It returns the following error:

include/plink2_base.h:85:6: error: #error "gcc 8.3 is known to have a miscompilation bug that was fixed in 8.4."
 #    error "gcc 8.3 is known to have a miscompilation bug that was fixed in 8.4."

Do you have a suggestion on how to address?

Thank you

**Comment by chrchang** [comment]
Either upgrade the version of gcc on your system, or install a precompiled binary package.
