### ISSUE TITLE
Can't run anny PLINK command on Ubuntu 22.04

### ISSUE THREAD

**Issue by MatusBuci** [chrchang/plink-ng#256]
Hey all,
Recently I have installed PLINK 1.9 on my Ubuntu 22.04 laptop and every time I've tried any command both on terminal and RStudio I've received the following message listed below. I have been working with PLINK on Windows for some time and I'm new to Linux. Can you explain to me please what might be the cause of this problem and give me some advice on how to solve it ? Thanks.

> system("plink")
PLINK v1.90p 64-bit (13 Feb 2023)            www.cog-genomics.org/plink/1.9/
(C) 2005-2023 Shaun Purcell, Christopher Chang   GNU General Public License v3

  plink <input flag(s)...> [command flag(s)...] [other flag(s)...]
  plink --help [flag name(s)...]

Commands include --make-bed, --recode, --flip-scan, --merge-list,
--write-snplist, --list-duplicate-vars, --freqx, --missing, --test-mishap,
--hardy, --mendel, --ibc, --impute-sex, --indep-pairphase, --r2, --show-tags,
--blocks, --distance, --genome, --homozyg, --make-rel, --make-grm-gz,
--rel-cutoff, --cluster, --pca, --neighbour, --ibs-test, --regress-distance,
--model, --bd, --gxe, --logistic, --dosage, --lasso, --test-missing,
--make-perm-pheno, --unrelated-heritability, --tdt, --dfam, --qfam, --tucc,
--annotate, --clump, --gene-report, --meta-analysis, --epistasis,
--fast-epistasis, and --score.

"plink --help | more" describes all functions (warning: long).
> system("plink --bfile plink --goat --recode vcf --out plink_example")
PLINK v1.90p 64-bit (13 Feb 2023)            www.cog-genomics.org/plink/1.9/
(C) 2005-2023 Shaun Purcell, Christopher Chang   GNU General Public License v3
Error: Failed to open plink_example.log.  Try changing the --out parameter.

**Comment by chrchang** [comment]
Basic usage questions like this should be posted in the plink2-users Google group (https://groups.google.com/g/plink2-users ), not here.
