### ISSUE TITLE
File read error when converting .vcf to PLINK .ped and .map file

### ISSUE THREAD

**Issue by ryshi06** [chrchang/plink-ng#257]
Hi, I want to convert a large VCF file (~3.5TB) to PLINK ped and map format files. But I got the log file as pasted below:

`Random number seed: 1707568963
773685 MB RAM detected; reserving 386842 MB for main workspace.
--vcf: All_Cohorts_Case_Control_autosome-temporary.bed +
All_Cohorts_Case_Control_autosome-temporary.bim +
All_Cohorts_Case_Control_autosome-temporary.fam written.
39131578 variants loaded from .bim file.
6152 people (0 males, 0 females, 6152 ambiguous) loaded from .fam.
Ambiguous sex IDs written to All_Cohorts_Case_Control_autosome.nosex .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 6152 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.999982.
39131578 variants and 6152 people pass filters and QC.
Note: No phenotypes present.
--recode ped to All_Cohorts_Case_Control_autosome.ped +
All_Cohorts_Case_Control_autosome.map ... 
Error: File read failure.`

I have checked the input VCF is a valid file and it can be read successfully. Can you please guide me on this?

Thank you!

**Comment by chrchang** [comment]
1. Rerun with plink 2.0.  It will provide a more informative error message than "File read failure."
2. WHY ARE YOU TRYING TO DO THIS AT ALL??!!!  I cannot imagine a valid use case for using .ped+.map over .bed+.bim+.fam here.
