### ISSUE TITLE
Plink 1.9 fails to build on some architectures

### ISSUE THREAD

**Issue by daissi** [chrchang/plink-ng#26]
Hi,
Plink 1.9 is now in official Debian repository [1] but it fails to build [2-3] on some architectures (arm64, ppc64el, s390x, etc) due to a missing header (emmintrin.h).

So what do you think about this? Should I disable build for these architectures or it is possible to fix this missing header?

Best regards,
Dylan

[1] https://tracker.debian.org/pkg/plink1.9
[2] https://buildd.debian.org/status/package.php?p=plink1.9
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799471

**Comment by chrchang** [comment]
Plink 1.9 does not work on big-endian architectures (e.g. ppc).

On little-endian architectures lacking SSE2, the 32-bit build should work.

**Comment by gerddie** [comment]
As I  pointed out in the Debian bug, the failing builds are all 64 bit and I think it is because you use __LP64__ to decide whether to use SSE2 or not. I'm just preparing a patch for the Debian package to replace __LP64__ by __SSE2__. Afaik arm64 is low endian, and the non-sse2 code path should also work there.

**Comment by chrchang** [comment]
That should work as long as SSE2 is not ever defined for 32-bit builds.

**Comment by gerddie** [comment]
Currently in Debian this is the case, but I've just seen some code where blindly replacing LP64 by SSE2 will not result in th expected behaviour if we are on 64 bit and without SSE2. You don't have some kind of test suite to check something like this, do you?

**Comment by chrchang** [comment]
The code is currently written to support a 32-bit build without SSE2, and a 64-bit build with SSE2.  A 64-bit build without SSE2 would require extensive changes.

**Comment by chrchang** [comment]
I will add preprocessor directives today to make the build error out with a "produce a 32-bit build instead" message if LP64 is defined and SSE2 isn't.
