### ISSUE TITLE
Obtaining different results from the same data in different formats

### ISSUE THREAD

**Issue by salcc** [chrchang/plink-ng#265]
I obtain different results when reading the same data from files in different formats. All the format conversions and data readings are done using the plink2 CLI (PLINK v2.00a5.10LM 64-bit Intel (5 Jan 2024)) and the Python API (Pgenlib==0.90.2), but I don't know which step introduces the error. I am using Python 3.10.14 on Ubuntu 22.04.2 LTS.

## Example

1. Download [chromosome 21 data from the 1KG in .vcf.gz format](https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz).

2. Convert the file to bed and pgen with plink.

```bash
plink2 --vcf ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz --make-bed --out ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased
plink2 --vcf ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz --make-pgen --out ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased
```

3. Read them with Python and compare the obtained arrays:

```python
import numpy as np
import pgenlib as pg

num_variants = 976599
num_samples = 2548

# Read the data from the BED file
pgen_reader_bed = pg.PgenReader(str.encode("data/bed/ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased.bed"),
                                    raw_sample_ct=num_samples, variant_ct=num_variants)
genotypes_bed = np.empty((num_variants, 2 * num_samples), dtype=np.int32)
pgen_reader_bed.read_alleles_list(np.arange(num_variants, dtype=np.uint32), genotypes_bed)

# Read the same data from the PGEN file
pgen_reader_pgen = pg.PgenReader(str.encode("data/pgen/ALL.chr21.shapeit2_integrated_v1a.GRCh38.20181129.phased.pgen"),
                                    raw_sample_ct=num_samples, variant_ct=num_variants)
genotypes_pgen = np.empty((num_variants, 2 * num_samples), dtype=np.int32)
pgen_reader_pgen.read_alleles_list(np.arange(num_variants, dtype=np.uint32), genotypes_pgen)

print(np.array_equal(genotypes_bed, genotypes_pgen))
```

The result is `False`, indicating that the data is different, although coming from the same file.

**Comment by chrchang** [comment]
The .pgen preserves phase information, and read_alleles_list captures it.

**Comment by salcc** [comment]
I didn't know that bed files didn't preserve it. Thank you!
