### ISSUE TITLE
Persistent download URLs for built binaries?

### ISSUE THREAD

**Issue by espenhgn** [chrchang/plink-ng#267]
Dear @chrchang, 
The download URLs provided on the PLINK [homepage](https://www.cog-genomics.org/plink/2.0/) points to files pushed to s3.amazonaws.com, however, these no longer work when the software is updated (e.g., https://s3.amazonaws.com/plink2-assets/plink2_linux_x86_64_20240504.zip). 
Can these build assets be uploaded somewhere persistent, e.g., as uploads with each tag/version/release here with this repository?
My particular use case is Docker builds relying on these URLs, but it would be good to be able to access old(er) versions if necessary.

**Comment by chrchang** [comment]
https://s3.amazonaws.com/plink2-assets/alpha5/plink2_linux_x86_64_20240105.zip is expected to be persistent through 2027, unless a very serious bug is discovered.

When feature development is complete on the alpha 6 branch, its download links will be similarly persistent.

**Comment by espenhgn** [comment]
Thanks; we're likely better off building from source and specific git SHAs in our Docker recipes in the future.
