### ISSUE TITLE
pgenlibr: ReadList question 

### ISSUE THREAD

**Issue by gidiesse** [chrchang/plink-ng#268]
Hello, 

I have been trying to use pgenlibr::ReadList to load dosages from a .pgen file. 
The problem is that my file contains NAs, and I wanted to maintain these in the loaded file on R so I set meanimpute=FALSE.
However, the loaded data did not in fact contain any NAs and so it appeared that the dosages were converted. To test this, I loaded the data setting meanimpute=TRUE and the loaded data was exactly the same as the one loaded with the flag set to false. 
Essentially, it would seem that even if meanimpute = FALSE, the NA dosages are converted anyways. 
Any idea on why this is and how I could fix it? 

Thank you very much.

**Comment by chrchang** [comment]
I just tested pgenlibr::ReadList on a file with missing calls, and got the expected NAs.

Please post test data and commands for reproducing what you're seeing.

**Comment by gidiesse** [comment]
Thanks for your reply, I'm posting my code down below. I have sent you the data for this at the email linked to your github account. 
What I'm doing is first checking if there are NAs present in the data using the flag --missing and then importing the relevant table. Then I load the data using pgenlibr::ReadList with meanimpute=FALSE but the NAs disappear. I also run pgenlibr::ReadList with meanimpute=FALSE to do a comparison and in fact at the end when I do an identical between the data read with meanimpute=TRUE and the data read with meanimpute=FALSE, I get TRUE. 

Please note that I am using plink2 ( I know it says plink, but this is a misnomer from when I loaded it onto my computer)

library(pgenlibr)
library(genio)

# Check if there are missing values in the pgen data with plink2 flag --missing
system("plink --pfile 10_kb_data --missing")
vmiss <- read.table("plink2.vmiss", header=F)

# Now we want to read the same data in pgen format with pgenlibr 
pvar <- NewPvar("10_kb_data.pvar")
pgen <- NewPgen("10_kb_data.pgen", pvar=pvar)

variant_subset <- c(1:49)

# With meanimpute=FALSE 
geno_mat <- ReadList(pgen, variant_subset, meanimpute = FALSE)
length(which(apply(geno_mat, 1, function(row) any(is.na(row)))))

# With meanimpute=TRUE
geno_mat2 <- ReadList(pgen, variant_subset, meanimpute = TRUE)
length(which(apply(geno_mat2, 1, function(row) any(is.na(row)))))

# Are they the same?
identical(geno_mat, geno_mat2)

**Comment by chrchang** [comment]
This is because plink2 --missing reports only hard-call missingness by default, to maximize similarity with plink 1.x.  See https://www.cog-genomics.org/plink/2.0/formats#vmiss ; I will add a note about this to https://www.cog-genomics.org/plink/2.0/basic_stats#missing .

You can add e.g. "vcols=+nmissdosage,+fmissdosage" to see that there are no missing dosages in your fileset.

**Comment by gidiesse** [comment]
Thank you so much for your prompt reply and explanation. One more question, how come there was no difference when I used pgenlibr::ReadList with meanimpute = TRUE and instead with meanimpute = FALSE?

**Comment by chrchang** [comment]
Because there were no missing dosages to impute.

**Comment by gidiesse** [comment]
Yes thank you, I have now verified this using the spec scols=+nmissdosage,+fmissdosage together with —missing command. 
One more question, I am observing a different behavior for other commands such as --geno and --freq , do you know whether these commands also work by converting to hard calls instead of using dosages?
Thanks so much.

**Comment by chrchang** [comment]
--freq takes dosage into account when they're available.
--geno dosage-handling is explicitly documented: https://www.cog-genomics.org/plink/2.0/filter#missing
