### ISSUE TITLE
Details about SNP pruning

### ISSUE THREAD

**Issue by KehaoWu** [chrchang/plink-ng#27]
When a pair of SNPs', A and B, r2 > 0.2, which one will be removed?

**Comment by chrchang** [comment]
The lower-MAF SNP is pruned.  If the MAFs are equal, the later-position SNP is pruned.

**Comment by KehaoWu** [comment]
Is it possible that incorporate p values or function information into SNP prunning?
For example, the smaller p-value SNP is pruned. If the p-values are equal, the intergenic SNP is pruned.

**Comment by chrchang** [comment]
You can currently get this behavior by creating an artificial set of "MAF estimates" which are a function of p-value and gene positions, and loading that with --read-freq.  (Just make sure to not include any filters which actually depend on MAF in your run...)

**Comment by KehaoWu** [comment]
Good idea! Thank you!
