### ISSUE TITLE
`--update-sex` does not assume FID to be 0 like `--keep`

### ISSUE THREAD

**Issue by BinglanLi** [chrchang/plink-ng#276]
### Working `--keep` for VCF input
Given a VCF input, the following file id list file `sample_id.txt` works when you use `--keep` to filter samples based on IDs. 
```
sample1
sample2
sample3
```
Plink2 correctly recognizes and interprets these as IIDs for the input sample.

### inconsistent sample ID interpretation between `--update-sex` and `--keep`
When I need to update the sex information, the following command won't work:
```
plink2 --vcf input.vcf --keep sample_id.txt --update-sex sex_update.tsv male0
```
Here is what `sex_update.tsv` looks like originally
```
sample1 0
sample2 0
sample3 1
```

### (Not working) test 1: specify sex column
```
plink2 --vcf input.vcf --keep sample_id.txt --update-sex sex_update.tsv col-num=2 male0
```
This reports an error saying that the column number is too small. So, PLINK2 does not assume FID to be 0 like what it does for `--keep`

### (Working) test 2: specify --double-id
```
plink2 --vcf input.vcf --keep sample_id_two_column.txt --update-sex sex_update_two_column.tsv male0 --double-id
```
In this test, the sex update file is updated to have two IID columns:
```
#sex_update_two_column.tsv
sample1 sample1 0
sample2 sample2 0
sample3 sample3 1
```
Similarly, the sample id file has to have two columns.
```
sample1 sample1
sample2 sample2
sample3 sample3
```
This way, PLINK2 successfully updates the sex for the input samples. The solution seems to work because `--update-sex` file has to have two ID columns.

**Question**: 
1. Why `keep` assumes FID to be 0, while `update-sex` does not? Can they have the same default behavior of assuming FID?
2. Otherwise, it will be beneficial to clarify in the documentation for `--update-sex` that it has to have two ID columns and people can use 0 as the FID for VCF.

**Comment by chrchang** [comment]
Your suggestion does not generalize to other col-num= values.

In general, you should provide a header line with "#IID" as the first column when you want plink2 to recognize that your IDs are single-part.  --keep is an exception because there are no non-ID columns.
