### ISSUE TITLE
Missing flags in the latest build.

### ISSUE THREAD

**Issue by VectorFrankenstein** [chrchang/plink-ng#278]
Hello,

I have, on my machine, Plink2 version `PLINK v2.00a6LM AVX2 Intel (5 Feb 2024)` which has access to the `--ld-snp` - which is in line with the documentation found here https://www.cog-genomics.org/plink/2.0/ld.

I have a colleague who has `Plink2` version `PLINK v2.00a6LM AVX2 Intel (26 May 2024)` which also has access to the flag `--ld-snp` as

```
 ~/bin/plink2 --help --ld-snp
PLINK v2.00a6LM AVX2 Intel (26 May 2024)       www.cog-genomics.org/plink/2.0/
(C) 2005-2024 Shaun Purcell, Christopher Chang   GNU General Public License v3

--ld-snp <var. ID>   : Restrict the first variant in --r[2]-[un]phased
--ld-snps <varID...>   variant-pairs to a limited set.  --ld-snp specifies
--ld-snp-list <file>   a single ID, --ld-snps accepts one or more ranges
                       (same syntax as --snps), and --ld-snp-list specifies a
file to load variant IDs from.
```

But a second colleague of mine just built `Plink2` from source for version `PLINK v2.00a5.14LM 64-bit Intel (20 Aug 2024)` but it does not have access to the flag `--ld-snp` according to the error message they are getting

```
LINK v2.00a5.14LM 64-bit Intel (20 Aug 2024)  www.cog-genomics.org/plink/2.0/
(C) 2005-2024 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to AASDF.log.
Options in effect:
  --bfile DRIP_284samples_final_maf_cleaned_windowd_59274174
  --ld-snp Chr_5_BP_59274174
  --ld-window-kb 9999999
  --ld-window-r2 0.5
  --out AASDF
  --r2-phased

Start time: Thu Sep 19 12:07:25 2024
Error: Unrecognized flag ('--ld-snp').
For more info, try "plink2 --help <flag name>" or "plink2 --help | more".
```

- Is this flag being sunset? If so what is it being replaced with?
- Is something wrong with my second colleague's installation?

Sincerely,
Rijan

**Comment by chrchang** [comment]
5.14 is less than 6.
