### ISSUE TITLE
macOS: Impossible to open plink2

### ISSUE THREAD

**Issue by Will-Tyler** [chrchang/plink-ng#279]
### Description

I am trying to run plink2 on my MacBook Air. I downloaded plink2 from [here](https://www.cog-genomics.org/plink/2.0/) by selecting the download link for Alpha 5.14 final for macOS M1.

When I try to run plink2 (`./plink2`), macOS displays a message saying that Apple cannot verify that plink2 does not contain malicious software and that the software needs to be updated.

### Machine details

```
OS: macOS 14.6.1 23G93 arm64
Host: MacBookAir10,1
Kernel: 23.6.0
Uptime: 15 days, 1 hour, 37 mins
Shell: zsh 5.9
CPU: Apple M1
GPU: Apple M1
```

**Comment by chrchang** [comment]
Compile from source if you are concerned about this.

**Comment by Will-Tyler** [comment]
It is not just a concern. macOS will not let me run the downloaded plink2 because of this.

I was able to install a working plink2 through [brewsci/bio](https://github.com/brewsci/homebrew-bio), which I learned about through #253, not through any documentation.

In my opinion, this issue should remain open because the installation instructions do not work.

**Comment by chrchang** [comment]
Apple has recently made this harder for users, but no, it's not impossible.  If it ever becomes impossible, I may stop supporting macOS.

**Comment by ShashaankV** [comment]
For macOS, do this:
1. try to run plink2 (or 1.x) and let it throw an error
2. then in Settings go to Privacy and Security, scroll down until you see a comment about plink2 being blocked, click Allow Anyway
3. you should now be able to run plink 2 (or 1.x)

<img width="703" alt="plink2macOS" src="https://github.com/user-attachments/assets/f0212355-43f5-433e-a930-b7262f493fe8">
