### ISSUE TITLE
Error when convert IMPUTE5 BGEN to BFILE or VCF

### ISSUE THREAD

**Issue by weichisyu** [chrchang/plink-ng#280]
Hi, 
I encountered an error: `File appears to be corrupted.` when I tried to convert a BGEN file (generated by IMPUTE5) to either a BFILE or VCF. 
However, I was able to use QCTOOLv2 to convert it to a VCF file.

My command:
```
/mnt/data/plink-ng-2.00a5.14/2.0/bin/plink2 \
--bgen part-00000-ukb500samples_impute_impu.bgen  ref-first \
--make-bed \
--out bgenTobed \
--threads 1
```
```
PLINK v2.00a5.14 64-bit (20 Aug 2024)          www.cog-genomics.org/plink/2.0/
(C) 2005-2024 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to bgenTobed.log.
Options in effect:
  --bgen part-00000-ukb500samples_impute_impu.bgen ref-first
  --make-bed
  --out bgenTobed
  --threads 1

Start time: Thu Oct  3 05:45:05 2024
64301 MiB RAM detected, ~60204 available; reserving 32150 MiB for main
workspace.
Using 1 compute thread.
--bgen: 187150 variants detected, format v1.3.
--bgen: 500 sample IDs written to bgenTobed-temporary.psam .
--bgen: 187k variants scanned.
Error: part-00000-ukb500samples_impute_impu.bgen read failure: File appears to
be corrupted.
End time: Thu Oct  3 05:45:05 2024
```

I also ran the following command to check whether it contains (illegal) empty ID values, but it returned nothing.
(the out.vcf was converted by QCTOOLv2 from this BGEN file)
```cat out.vcf | grep -v "^#" | awk '{FS = "\t"; if ($3 == "") print $0}'```
Here is the first record in the out.vcf file, which was converted by QCTOOLv2 from a BGEN file generated by IMPUTE5.
```
1       10177   .;1:10177_A_AC  A       AC      .       .       .       GP      0.482353,0.517647,0.592157,0.407843
```
Many thanks,
Weichi

**Comment by chrchang** [comment]
Is it possible for you to send me a BGEN (doesn't have to be this one, could be another one based on fake data) that triggers this error in plink2 but not QCTOOLv2?
If not, would it be possible for you to run a sequence of debug builds I post?

**Comment by chrchang** [comment]
(also, please post the QCTOOLv2 command line, and the output of "wc -l out.vcf".)

**Comment by weichisyu** [comment]
I also found that the total number of variants in out.vcf differs from what PLINK2 detected (--bgen: 187,150 variants detected, format v1.3).
```
cat out.vcf |grep -v "^#"|wc -l
187095
```

**Comment by weichisyu** [comment]
This is a BGEN file that triggers this error in plink2 but not QCTOOLv2.
(This BGEN was generated by IMPUTE5, and the data source is the example file within IMPUTE5 bundle)
[imputed.bgen.zip](https://github.com/user-attachments/files/17242084/imputed.bgen.zip)

**Comment by chrchang** [comment]
Interesting.  The issue is that the header overstates the number of variants in the BGEN ("An unsigned integer M..." in https://www.chg.ox.ac.uk/~gav/bgen_format/spec/latest.html ).

If, in practice, programs like IMPUTE5 are saving an upper bound instead of an exact count here, I will make future plink2 builds print a warning instead of an error in this situation.

**Comment by chrchang** [comment]
Today's build adds a --lax-bgen-import flag to tolerate this; let me know if you still have any problems.

**Comment by weichisyu** [comment]
Hi, sorry for the late reply. 
I was able to use the new version of PLINK2 to successfully convert the IMPUTE5 BGEN file to BFILE with --lax-bgen-import flag. 
Thank you for your kind help.
