### ISSUE TITLE
lfile 3+ different alleles error

### ISSUE THREAD

**Issue by dwaggott** [chrchang/plink-ng#29]
I'm struggling getting some illumina genotypes to load. I've converted the gtreports to lgen format but keep getting the 3+ allele error. In the example below all that's there is A and 0. Specifying `--missing-genotype 0` didn't seem to help.

[mega.map](https://gist.github.com/e40fd5af97308ab94d8b)
[mega.fam](https://gist.github.com/762c9d631fba28a91a2d)
[mega.lgen](https://gist.github.com/d8c59edbe97ba65e8c0)

`plink --lfile mega`
Error: Variant '1:10001102-G-T' in .lgen file has 3+ different alleles

This was using code from Feb 2016. Using a version from 2014 worked.

**Comment by dwaggott** [comment]
Update: So the code from 2014 works loading lgen files but fails when trying trying to do a multi file merge using `--merge-list`. The genotyping rate ends up being zero. Switching back to the 2016 version for the merge works.

**Comment by chrchang** [comment]
Hi,

Can you send me a .lgen fileset to replicate this issue with?  Thanks.

**Comment by dwaggott** [comment]
Do the gist files in the first post work?

**Comment by chrchang** [comment]
The .map and .fam links work, but the .lgen link fails.

**Comment by dwaggott** [comment]
Right, sorry.

https://gist.github.com/74f13dc64fc3c3047c58

**Comment by chrchang** [comment]
This should be fixed in the 13 March builds; let me know if you still have any problems.

**Comment by ALSHAWI** [comment]
Hi every one 

I made 3 files .lgen,.map & .fam ,so I tried to make PED and MAP file by plink command ,so here I  faced same problem in this post of dwaggott 

**Error: Variant 'ARS-BFGL-BAC-27364' in .lgen file has 3+ different alleles.**

Moreover,the command that I used it 
./plink --lfile rustaqi22 --cow --recode


can any one advice how to deal with this  error?

Thanks

**Comment by ALSHAWI** [comment]
Hi every one

I tried to make PED&MAP files by PLINK from three files that I made it .lgen ,.map &.fam So,error appeared

Error: Variant 'ARS-BFGL-BAC-27364' in .lgen file has 3+ different alleles.

So,the command that I used it ./plink --lfile rustaqi22 --cow --recode

Moreover,example below of rows of my .lgen file

Rustaqi 88 ARS-BFGL-BAC-10172 B B Rustaqi 88 ARS-BFGL-BAC-1020 A B Rustaqi 88 ARS-BFGL-BAC-10245 B B

Could any one advice how to deal with this point?

Thanks

**Comment by ALSHAWI** [comment]
Hi every one

I tried to make PED&MAP files by PLINK from three files that I made it .lgen ,.map &.fam So,error appeared

Error: Variant 'ARS-BFGL-BAC-27364' in .lgen file has 3+ different alleles.

So,the command that I used it ./plink --lfile rustaqi22 --cow --recode

Moreover,example below of rows of my .lgen file

Rustaqi 88 ARS-BFGL-BAC-10172 B B Rustaqi 88 ARS-BFGL-BAC-1020 A B Rustaqi 88 ARS-BFGL-BAC-10245 B B

Could any one advice how to deal with this point?

Thanks

**Comment by iceback** [comment]
I'm using v1.9 from 20 Jun 2014. Would the fix of 13Mar2016 also account for .lgen import mistaking first two columns as marker id?
The log:
Working directory: /uufs/chpc.utah.edu/common/home/camp-group1/submissions/dbGAP/cll/denovo
Start time: Mon Mar 19 09:23:16 2018

Random number seed: 1521472996
64386 MB RAM detected; reserving 32193 MB for main workspace.
Processing .lgen file... Error: Variant '9999 101862' in .lgen file has 3+ different alleles.

The .lgen, wherein I've tried both tabs and spaces (shown):
9999 103355 200003 A G
9999 103389 200003 A A
9999 103590 200003 A A
9999 100563 200003 A G
9999 100698 200003 A A
9999 103720 200003 A G
9999 101182 200003 A A
9999 101414 200003 A G
9999 100682 200003 A A
9999 103789 200003 A A

**Comment by chrchang** [comment]
Yes, this works in recent plink 1.9 builds.

**Comment by iceback** [comment]
Yes, thanks, I tried the "stable" release. The age old problem of misleading error messages. Turns out the data was malformed; "-" needs to be "0".  I suspect this was not the case when last I used plink (2014).

**Comment by jingydz** [comment]
$ plink --version
PLINK v1.90b6.9 64-bit (4 Mar 2019)

Error: 1 variant with 3+ alleles present.
* If you believe this is due to strand inconsistency, try --flip with
  merge-merge.missnp.
  (Warning: if this seems to work, strand errors involving SNPs with A/T or C/G
  alleles probably remain in your data.  If LD between nearby SNPs is high,
  --flip-scan should detect them.)
* If you are dealing with genuine multiallelic variants, we recommend exporting
  that subset of the data to VCF (via e.g. '--recode vcf'), merging with
  another tool/script, and then importing the result; PLINK is not yet suited
  to handling them.

The version of PLINK software that I am using is 1.9, and I have encountered this issue as well. Could you please provide me with some advice?

**Comment by chrchang** [comment]
Please post basic usage questions in the [plink2-users Google group](https://groups.google.com/g/plink2-users), not here.
