### ISSUE TITLE
vcf --set-missing-var-ids Duplicate ID error

### ISSUE THREAD

**Issue by dwaggott** [chrchang/plink-ng#31]
I'm seeing a duplicate ID error with the following vcf snippet. It looks like the set-missing-var-id isn't respecting REF/ALT order?? Easy enough to just add the ideas in bash.

`plink --vcf test.vcf --set-missing-var-ids @:#_\$1_\$2  --make-bed --out test --double-id --keep-allele-order`

https://gist.github.com/f747f9f54c14042ec0475c997299dfe4

**Comment by chrchang** [comment]
That is correct; I decided to use alphabetic rather than A1/A2 order for now since plink 1.x normally doesn't try to preserve A1/A2 order.  So yes, you should use a short bash script for now if you want REF/ALT-based names.

(plink 2.0 fixes this.)

**Comment by dwaggott** [comment]
Okay, looking forward to 2.0. Is there a dev repo?

**Comment by chrchang** [comment]
Not yet, but I'll let you know when that changes.

**Comment by chrchang** [comment]
Forgot to comment here that the plink 2.0 dev repo is now visible.
