### ISSUE TITLE
`--ld-snp` fails silently if there is missing data in focal SNP 

### ISSUE THREAD

**Issue by ngcrawford** [chrchang/plink-ng#34]
It just leaves an empty file. This is for plink2 (e.g., PLINK v1.90b3h). My command looks like the following. 

```
    plink \
    --vcf my.vcf.gz \
    --snps-only \
    --keep-allele-order \
    --keep samples.2.keep \
    --geno 0.05 \
    --r2 dprime with-freqs \
    --ld-window-r2 0.0 \
    --ld-window 1000000 \
    --ld-window-kb 1000000 \
    --ld-snp rsID_1232152 \
    --out my.output
```

If I manually excluded the samples containing `./.` using `--remove`, then it seems to work.

**Comment by chrchang** [comment]
Hmm, I was unable to reproduce this problem on a synthetic dataset with some missing genotypes.  Can you check whether the problem still exists with the latest build?  If so, can you send me a small dataset I can use to replicate the issue?

**Comment by ngcrawford** [comment]
I think it's only an issue with small datasets (e.g., ~15 individuals or less).

**Comment by chrchang** [comment]
I still wasn't able to reproduce this with an 11-sample dataset.  Can you send me the dataset which is exhibiting this problem on your end?
