### ISSUE TITLE
Segfault with --remove-cluster-names

### ISSUE THREAD

**Issue by BertrandServin** [chrchang/plink-ng#35]
Hi, 

when running as such 
plink --bfile plink --remove-cluster-names SomePop --make-bed --out newplink --family

The call ends up with a segfault (tested on several datasets). It seems to take a very looooong time to get there though.

Easy work around is to
grep SomePop plink.fam > SomePop.indiv
and then just use 
plink --remove SomePop.indiv

but I figured I should tell you about the bug.

Thanks for the software btw :)

**Comment by chrchang** [comment]
Thanks for the note.  This bug should be fixed with the latest commit; let me know if you still have any problems.

**Comment by jlc-christie** [comment]
Was this ever fixed? I can write a fix if not.

**Comment by chrchang** [comment]
Yes, I haven't heard anyone report this problem after the Sep 10 commit.
