### ISSUE TITLE
Binary file format inconsistencies between 1.07 and 1.9

### ISSUE THREAD

**Issue by Chris1221** [chrchang/plink-ng#37]
Hi, thanks for putting so much work into a fantastic piece of software. I've been working on using `plink` style binary files in one of my own programs and have come across an inconsistency in the documentation that I think could use some clarification. 

[On the original `plink1.07` webpage](http://pngu.mgh.harvard.edu/~purcell/plink/binary.shtml), the `.bed` format is given to have the following conversions:

```
For the genotype data, each byte encodes up to four genotypes (2 bits per genoytpe). The coding is
     00  Homozygote "1"/"1"
     01  Heterozygote
     11  Homozygote "2"/"2"
     10  Missing genotype
```

[While on the `plink1.9` webpage](https://www.cog-genomics.org/plink2/formats#bed), the conversion table is given as follows:

```
The two-bit genotype codes have the following meanings:

00	Homozygous for first allele in .bim file
01	Missing genotype
10	Heterozygous
11	Homozygous for second allele in .bim file
```

There seems to be some disagreement between the heterozygous and missing codings. 

I downloaded the `toy` data distributed with `plink1.9` and converted it to binary.

```
plink2 --bfile toy --make-bed --out toy
cat toy.ped

1 1000000000 0 0 1 1 0 0 1 1
1 1000000001 0 0 1 2 1 1 1 2

xxd -b toy.bed

0000000: 01101100 00011011 00000001 00001101 00001011           l....

cat toy.bim

1       rs0     0       1000    0       1
1       rs10    0       1001    2       1
```

After excluding the first two magic number bytes and the format byte, we proceed to look at the first (fourth) byte which reads 

```
rs0
10 -  missing (1.07) / heterozygous (?) (1.9)
11 - homozygous second allele
...skip...

rs10
11 - homozygous second allele 
01 - heterozygote (1.07) / missing (?) (1.9)
...skip...
```

So, it seems as though this simple example supports the original `v1.07` coding, unless I have misinterpreted it.

- Was there a change in the coding between `plink1.07` and `plink1.9` for missing / heterozygous? If so, is there any way to distinguish the two and account for that?

**Comment by chrchang** [comment]
The binary format is unchanged.  The difference lies in reading two-bit groups right-to-left vs. left-to-right; the plink 1.9 documentation is written in terms of left-to-right reading.

**Comment by Chris1221** [comment]
Oh my goodness, thank you. So sorry for a trivial question, and thanks for your help!
