### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by jmannau** [chrchang/plink-ng#40]
Hi,

I tried to update the Home Brew recipe to install Plink2 (https://github.com/Homebrew/homebrew-science/pull/5243). I have linked to you commit https://github.com/chrchang/plink-ng/commit/96f3637b62f4fddcf1e5a16929b77c637867d8cd as the source for version b3.46 however this is not a preferred option.

Is it possible to tag releases so that GitHub can create a tarball automatically for that release?

Cheers!

**Comment by chrchang** [comment]
Okay, next week's stable build will be tagged as a release.  This is good timing since it will come with some other changes to the repository structure...

**Comment by chrchang** [comment]
A new tagged release has been created.

**Comment by jmannau** [comment]
Thanks @chrchang! I have updated the home-brew package with 1.9b4.
