### ISSUE TITLE
[Request] Support Rserve connections through unix domain sockets

### ISSUE THREAD

**Issue by jkaessens** [chrchang/plink-ng#41]
Currently, the `--R` option allows to connect to a local TCP service in a port specified by `--R-port` or the default one. However, when running the Plink-Rserve combination on shared systems such as cluster computing nodes, Rserve regularly fails as the default port is already taken by some other process, be it Rserve or not. Therefore, Rserve also allows to use a unix domain socket instead, where no clash will happen with other users.

Technically, in `Rconnection.cc`, connecting to those sockets is already implemented. If the port is negative, the given IP string is intepreted as a path to a unix domain socket and the family correctly set to `AF_LOCAL` instead if `AF_INET`. Unfortunately, the option parser in `plink.c` for `--R-port` expects a positive number and an IP (or host name) cannot be given at all.

It would be nice if someone could add the additional option, e.g. `--R-host`, and lift the positive-integer restriction on the `--R-port` option. As a side effect, that would also allow connecting to remote Rserve instances.

**Comment by chrchang** [comment]
Sure, I'll try to add this today or tomorrow.

**Comment by chrchang** [comment]
I went ahead and added --R-socket to the development build (no --R-port -1 needed, so I restored the positive integer check); let me know if it works for you.

**Comment by jkaessens** [comment]
Marvelous. I had it running through the night on our cluster and all went fine in the last 10,000 invocations.

Thanks a lot!
