### ISSUE TITLE
[request] append_alleles_list, etc. in python API for PLINK2

### ISSUE THREAD

**Issue by yk-tanigawa** [chrchang/plink-ng#42]
Is it possible that PLINK2 python API can support a functionality to write multiple variants?

PgenReader currently has `read_alleles_list`, `read_alleles_range`, etc. and they are pretty useful. It would be great if there are some similar functions for PgenWriter as well.

**Comment by chrchang** [comment]
append_biallelic_batch(), append_alleles_batch(), etc. have been added to today's build; let me know if you have any problems with them.

**Comment by yk-tanigawa** [comment]
@chrchang Thanks for implementing the new functions.
I have tried the pgenlib.PgenWriter.append_alleles_batch() and found that it caused a seg fault. 
I also wrote a for loop to test pgenlib.PgenWriter.append_alleles() and it was also unsuccessful.
My test script and its output is listed below:

https://gist.github.com/yk-tanigawa/ea73b2ac63e20abe62bf4ba3f13c97e3

**Comment by chrchang** [comment]
Oops, divided by the wrong number when determining a few loop lengths.  Attempted fix is posted.
