### ISSUE TITLE
Bug Report - Medelian Error on Multiallelic Variants

### ISSUE THREAD

**Issue by MatthewMaher** [chrchang/plink-ng#47]
Starting from a multifamily joint-called VCF, I'm trying to use the '--mendel' option to detect mendelian errors based on pedigree information I supplied.  But by comparison to another method, it appears to be missing many such errors when there is a multi-allelic (more than one alt) variant with mend errors in multiple families on multiple variants.    I have boiled down an example in the attached zip file - a one variant VCF containing seven people over two families.  Each of the affecteds should be a mendelian error, but only the ones in the first family (601) get detected, the mendelian error in family 643 is not reported.  

But if you edit the VCF and change the two HET calls for the 601 children (0/2 --> 0/0), and repeat, then the error in family 643 IS reported. 

Thanks

[bugreport.zip](https://github.com/chrchang/plink-ng/files/1215028/bugreport.zip)

**Comment by chrchang** [comment]
PLINK 1.9 does not support multiallelic variants.  The goal is to make this work properly in PLINK 2.0.

**Comment by MatthewMaher** [comment]
thanks - that explains it.  Sorry, I should have read farther and figured that out myself.
