### ISSUE TITLE
Bfile parameter

### ISSUE THREAD

**Issue by ninaxhua** [chrchang/plink-ng#49]
Hello,
I'm following this [paper](http://www.nature.com/nprot/journal/v5/n9/full/nprot.2010.116.html) for QC filtering, but I'm running into an issue when I run this:
`plink --bfile 00_data/hgdp –-genome --out 01_QC/03_duplication/hgdp`
It outputs this error: 
`Error: --bfile accepts at most 1 parameter.`
But I don't understand why I'm receiving that error since I specified the prefix within the 00_data folder?

**Comment by chrchang** [comment]
The problem is with the first dash in "--genome": it's a special character
instead of the normal dash character recognized by plink.  Delete it and
this should work.

**Comment by aranyak111** [comment]
I want to create a 1000G/phase3/EUR_all reference panel in my Linux environment. I am new to using plink and population genetics. Can you please instruct me on how to do it? I require to do it for conducting the mt-cojo analysis. Please help.
