### ISSUE TITLE
--update-ids: 1 person updated. How update FID in .fam and .ped files?

### ISSUE THREAD

**Issue by angelaparodymerino** [chrchang/plink-ng#53]
Hi,

I converted my .cvf file into .bed/.fam/.bim format. For that I had to use --const-fid 0 because I was having this error message: Multiple instances of '_' in sample ID.

Then, all the families ID (FID) were set to '0'.

This is, however, causing me problems when I try to use Mega2, which throw me an error message because all FIDs are 0 and this is wrong because Mega2 is reading that all individuals belong to the same family. Anyway, what happens is that I need to edit FID so that each individuals as an unique FID (i.e FAM1, FAM2, FAM3..etc). Doing so, Mega2 will understand that all the individuals are unrelated (and hopefully I won't receive any error messages!).

I tried what it is explained here:[ ](http://zzz.bwh.harvard.edu/plink/dataman.shtml) (in the section 'update individuals information'). Specifically, I prepared a .txt file with four columns: old FID, old IID, new FID, new IID. It looks like this (only three first rows):

0	NWZ_106801_P03_WH01	FAM1	NWZ:106801:P03:WH01
0	NWZ_106801_P01_WD11	FAM2	NWZ:106801:P01:WD11
0	NWZ_106801_P03_WG01	FAM3	NWZ:106801:P03:WG01

Then I used this: $ plink2 -file myplink --update-ids EditFIDandIID.txt --make-bed --out myplinkRFfids

and this was what I got:

PLINK v1.90b3 64-bit (11 Jan 2015)         https://www.cog-genomics.org/plink2
(C) 2005-2015 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to myplinkRFfids.log.
8192 MB RAM detected; reserving 4096 MB for main workspace.
.ped scan complete (for binary autoconversion).
Performing single-pass .bed write (3412 variants, 265 people).
--file: myplinkRFfids-temporary.bed + myplinkRFfids-temporary.bim +
myplinkRFfids-temporary.fam written.
3412 variants loaded from .bim file.
265 people (0 males, 0 females, 265 ambiguous) loaded from .fam.
Ambiguous sex IDs written to myplinkRFfids.nosex .
**--update-ids: 1 person updated.**
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 265 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.99727.
3412 variants and 265 people pass filters and QC.
Note: No phenotypes present.

The problem is that this just updated 1 individuals!, as also showed in the .fam when I open it:

FAM1 NWZ:106801:P03:WH01 0 0 0 -9
0 NWZ_106801_P01_WD11 0 0 0 -9
0 NWZ_106801_P03_WG01 0 0 0 -9

Does anyone knows what am I doing wrong? and what can I do to update FID of all the individuals successfully?

Thanks in advance,

Ángela Parody-Merino

**Comment by chrchang** [comment]
What do you get if you type "wc -l EditFIDandIID.txt"?  If it's just 1, you need to change the linebreaks in that file to Unix/OS X style.

Otherwise, I'd have to look at myplink.fam and EditFIDandIID.txt to figure out what's going on.

**Comment by angelaparodymerino** [comment]
Hi chrchang,

Thanks for your answer.

I did what you said:
```
MacBook-Pro-de-Angela:261017 angelaparodymerino$ wc -l EditFIDandIID.txt
       0 EditFIDandIID.txt
```
Well, it didn't return 1, but 0, which sounds not right either. Therefore you must be right about the reason for the problem. However, I am quite new to all this, so I don't know how to solve it. I see two options:

1) Change linebreaks (as you said) of EditFIDandIID.txt file. I don't know if this is fast&easy to do for someone pretty new like me. Do you know how could I do this?

2) Redo the EditFIDandIID.txt file directly with the Unix/OS X style. Do you know how?

Thanks,

Cheers,

Ángela Parody-Merino
