### ISSUE TITLE
Bug in plink --merge-list using one ped/map file per sample

### ISSUE THREAD

**Issue by ekarlins** [chrchang/plink-ng#56]
I have a pipeline that generates a ped/map file for each sample using an Illumina gtc file and a python script that I wrote.  I then use ```plink --file samp1 --merge-list samps2_n.txt --make-bed --out AllSamps``` to merge all of the genotypes together.  I have found a few instances when the genotypes in the merged bed file are not 100% concordant with the genotypes in the original ped files.  It seems to only happen if samples are in a particular order in the ```--merge-list``` file, though I can't figure out if there is a pattern as to when it happens.

I have been able to replicate this bug using both "PLINK v1.90b4.10 64-bit (3 Nov 2017)" and "PLINK v1.90b3.32 64-bit (24 Feb 2016)".

After the merge I checked concordance of the original ped file with the merged file using ```--merge-mode 7``` and the concordance for 6 samples looked like this:
```sh
SC112442_PB100119_F03.concordance.log:674909 concordant, for a concordance rate of 0.970771.
SC112445_PB100119_E09.concordance.log:683633 concordant, for a concordance rate of 0.983495.
SC197867_PB100119_D10.concordance.log:687412 concordant, for a concordance rate of 0.989207.
SC198277_PB100119_E10.concordance.log:689111 concordant, for a concordance rate of 0.991734.
SC198278_PB100119_F10.concordance.log:690717 concordant, for a concordance rate of 0.993527.
SC198302_PB100119_H01.concordance.log:695791 concordant, for a concordance rate of 1.
```

So for the 6 samples above, there was only 1 sample that was the expected 100% concordant.  This was "samp1" in my example above.

I have files that I can send you to replicate the bug, though even compressed they seem to be too big to attach here.

Thanks,
Eric

**Comment by ekarlins** [comment]
For my example above PLINK v1.07 works as expected here.  Here is the concordance rate for the same 6 samples after merging the ped files using v1.07:

```
SC112442_PB100119_F03.OldPlink.log:695230 concordant, for a concordance rate of 1.
SC112445_PB100119_E09.OldPlink.log:695106 concordant, for a concordance rate of 1.
SC197867_PB100119_D10.OldPlink.log:694912 concordant, for a concordance rate of 1.
SC198277_PB100119_E10.OldPlink.log:694855 concordant, for a concordance rate of 1.
SC198278_PB100119_F10.OldPlink.log:695217 concordant, for a concordance rate of 1.
SC198302_PB100119_H01.OldPlink.log:695791 concordant, for a concordance rate of 1.
```

**Comment by chrchang** [comment]
Yes, please send the files to me at chrchang523 at gmail.  This sounds like a .ped-specific bug that wasn't noticed till now because --merge-list is normally used on .bed files, but fixing it would be a very high priority.

**Comment by chrchang** [comment]
(or post the files to Dropbox and send me a link, etc.)

**Comment by ekarlins** [comment]
Thanks!
I emailed you the files.

**Comment by chrchang** [comment]
Hmm, I don't see an email.

**Comment by ekarlins** [comment]
I resent from my gmail in case my NIH account didn't want to send the attachment.  Let me know if you received it.

**Comment by chrchang** [comment]
Got it this time, thanks.

**Comment by ekarlins** [comment]
Great.  Thanks for working on this!

**Comment by chrchang** [comment]
Should be fixed by 21ab4fa2; let me know if you still see any problems.

**Comment by ekarlins** [comment]
Thanks for fixing this so quickly!  I'll test the new release when I get a chance and close this issue if everything looks good.

Eric

**Comment by ekarlins** [comment]
This bug looks fixed to me too.  Thanks again!

I have an additional question about the .ped --merge-list, though.  It seems like this command takes a good bit of RAM.  On our system it has max memory of about 127GB per job.  And this is consistent whether we're merging 5 ped files or 5000.  Is this expected?

Eric

**Comment by chrchang** [comment]
plink 1.9 defaults to reserving half of available RAM as workspace memory, but you can change this with --memory [# of MB you want plink to use].  Unless you have very long variant IDs, 4-16 GB is usually enough.

**Comment by ekarlins** [comment]
Thanks!  That explains the memory usage since I'm running on 260GB nodes.  I'll close this issue since you fixed the bug in the new release.  Thanks again for fixing this issue and releasing a new version in less than a day!

Eric
