### ISSUE TITLE
--make-just-fam error : no variants remaining

### ISSUE THREAD

**Issue by nievergeltlab** [chrchang/plink-ng#57]
Hi

PLINK v1.90b5 gives an error when I try to make just a family file:

PLINK v1.90b5 64-bit (14 Nov 2017)
Options in effect:
  --fam dos_pts_PROM_mix_am-qc.hg19.ch.fl.chr10_027_030.out.dosage.fam
  --make-just-fam
  --memory 500
  --out dos_pts_PROM_mix_am-qc.hg19.ch.fl.chr10_027_030

Start time: Mon Dec  4 21:48:55 2017

Random number seed: 1512420535
64384 MB RAM detected; reserving 500 MB for main workspace.
3451 people (0 males, 3451 females) loaded from .fam.
3451 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 3414 founders and 37 nonfounders present.
**Error: No variants remaining.**

End time: Mon Dec  4 21:48:55 2017

This doesn't occur in an earlier version,

PLINK v1.90b3y 64-bit (4 Nov 2015)         https://www.cog-genomics.org/plink2
(C) 2005-2015 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to test2.log.
Options in effect:
  --fam dos_pts_PROM_mix_am-qc.hg19.ch.fl.chr9_141_144.out.dosage.fam
  --make-just-fam
  --memory 500
  --out test2

32096 MB RAM detected; reserving 500 MB for main workspace.
3451 people (0 males, 3451 females) loaded from .fam.
3451 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked.
Before main variant filters, 3414 founders and 37 nonfounders present.
**Among remaining phenotypes, 1698 are cases and 1753 are controls.
--make-just-fam to test2.fam ... done.**

I am guessing that --allow-no-vars would function as a work-around.

Also, is it possible to export a new .fam file when you filter down a dosage file? 

e.g. to get a new family file after removing subjects:
plink --dosage filename.fam --fam filename.fam --remove remove.subjects --write-dosage --out dose_revised

Thanks
Adam

**Comment by chrchang** [comment]
Oops.  Just posted a patch for this, binaries will be updated later today.

As for the dosage file operation you mention, use plink 2.0 --import-dosage.  It supports all regular plink operations, while plink 1.x --dosage supports very little.

**Comment by nievergeltlab** [comment]
Cool, thanks!
