### ISSUE TITLE
Plink 1.9 --test-missing gives incomplete variant report

### ISSUE THREAD

**Issue by lea-urpa** [chrchang/plink-ng#59]
Hello! I am using `--test-missing` to compare differential missingness in variants between cases vs. controls. I have ~200,000 variants that ought to be compared, but the `.missing` result file contains only ~77,000 variants with reported frequencies.

These results have previously been pruned for excessive missingness, heterogeneity in individuals, etc. 

I am running PLINK v1.90b4.6 64-bit (15 Aug 2017) on Linux Red Hat Enterprise. Relevant output from the `--test-missing`command:

    196849 variants loaded from .bim file.
    1487 people (739 males, 748 females) loaded from .fam.
    1487 phenotype values loaded from .fam.
    Before main variant filters, 1083 founders and 404 nonfounders present.
    Warning: 1039 het. haploid genotypes present (see
    merged_QCd_batchcomparison.hh ); many commands treat these as
    missing.
    Total genotyping rate is 0.999216.
    196849 variants and 1487 people pass filters and QC.
    Among remaining phenotypes, 508 are cases and 979 are controls.
    Writing --test-missing report to merged_QCd_batchcomparison.missing
    ... done.

Any ideas why the report is truncated?

**Comment by chrchang** [comment]
Variants with no missing genotypes are also excluded from the --test-missing report.

**Comment by lea-urpa** [comment]
Ah great, I missed that line in the documentation. That exactly answers my question, thanks!
