### ISSUE TITLE
Plink hangs

### ISSUE THREAD

**Issue by Linnm00** [chrchang/plink-ng#60]
(I am new to using plink and not formally trained in bioinformatics), first time trying to use plink it was connecting to web for a long time without anything happening, so i tried --noweb. Without realizing my error I am now stuck. Plink hangs and I can not write any commands, please advise! 
See below where it gets stuck

/Users/linnmaristorengen/plink_mac/plink ; exit;
PLINK v1.90b5.2 64-bit (9 Jan 2018)            www.cog-genomics.org/plink/1.9/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3

  plink [input flag(s)...] {command flag(s)...} {other flag(s)...}
  plink --help {flag name(s)...}

Commands include --make-bed, --recode, --flip-scan, --merge-list,
--write-snplist, --list-duplicate-vars, --freqx, --missing, --test-mishap,
--hardy, --mendel, --ibc, --impute-sex, --indep-pairphase, --r2, --show-tags,
--blocks, --distance, --genome, --homozyg, --make-rel, --make-grm-gz,
--rel-cutoff, --cluster, --pca, --neighbour, --ibs-test, --regress-distance,
--model, --bd, --gxe, --logistic, --dosage, --lasso, --test-missing,
--make-perm-pheno, --tdt, --qfam, --annotate, --clump, --gene-report,
--meta-analysis, --epistasis, --fast-epistasis, and --score.

'plink --help | more' describes all functions (warning: long).
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process executed]

**Comment by ShiKANY** [comment]
HI, I got the same problem. Did anyone figure out what happened here?

**Comment by chrchang** [comment]
plink is a command-line program.  If you don't know what that means, you should spend at least a day learning the basics of using command-line programs before trying to use plink again.
