### ISSUE TITLE
Beta or OR in logistic regression

### ISSUE THREAD

**Issue by SiyangLiu** [chrchang/plink-ng#66]
Dear Chang,

I am using the following command for gwas analysis.
plink --dosage $gprobs.file --fam $fam --covar $cov --covar-name PC1-PC5 --out $out

Does the BETA column in the output file represents the regression coefficient or the OR value?  Is the SE column for the effect or for the OR? I tried to search the answers in the source code but haven't found the clue. 

Thank you very much in advance. 

Best,
Siyang

**Comment by SiyangLiu** [comment]
Thanks Chang. My result has a column 'BETA'. However, all the BETA has an positive value with a mean/median around 1. 

 Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2847  0.9798  1.0002  1.0018  1.0213  4.6970 

Will there be any situation that the column is BETA but the reporting value is the OR? I am using exactly the command that I mentioned above.

Thanks.

Best,
Siyang

**Comment by chrchang** [comment]
Hi,

Can you post the full .log file from your run?
