### ISSUE TITLE
PLINK2: --genome not recognized

### ISSUE THREAD

**Issue by samuelandjw** [chrchang/plink-ng#67]
I'm using development build (April 16) on Linux 64-bit. When I typed in `plink2 --genome`, I got

```
PLINK v2.00a2LM 64-bit Intel (16 Apr 2018)     www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --genome

Start time: Wed Apr 18 10:01:28 2018
Error: Unrecognized flag ('--genome').
For more info, try 'plink2 --help [flag name]' or 'plink2 --help | more'.
```

According to the documentation (https://www.cog-genomics.org/plink2/ibd), `--genome` should be available.

**Comment by samuelandjw** [comment]
@chrchang Thanks for the clarifications. I will use PLINK v1.9 for the time being.

**Comment by chrchang** [comment]
plink2 alpha builds are intended to be a companion to, rather than a replacement for, the v1.9 binary.  In particular, plink2's --make-king-table command is not a full substitute for --genome (no Z0/Z1/Z2 estimates), but if you're just interested in PI_HAT it's usually a significant improvement.
