### ISSUE TITLE
What is the difference between chromosome X and autosomes using --assoc？

### ISSUE THREAD

**Issue by JJMaggie** [chrchang/plink-ng#68]
hello,

My shell is 
```
plink --vcf GWAS.23chr.vcf \
                  --a2-allele GWAS.23chr.vcf.ref \
		  --keep-allele-order \
		  --double-id \
		  --set-missing-var-ids @:# \
		  --allow-no-sex \
		  --update-sex pheno.gender.txt 3 \
		  --pheno pheno.gender.txt --mpheno 4 \
		  --recode \
		  --make-bed \
		  --out vcf2plink && \
plink --file vcf2plink --maf 0.05 --geno 0.1 --hwe 0.000005 --mind 0.2 --make-bed --recode --out plink.filter &&\
plink --bfile plink.filter --assoc --out plink_asso --allow-no-sex
```
The pheno.gender.txt file contains gender information, how dose PLINK consider male and female samples for chromosome X results?

thank you
best

**Comment by chrchang** [comment]
--assoc is based on allele counts.  Males have only 1 allele per variant on chrX, while females have 2.

**Comment by JJMaggie** [comment]
so we calculate the number of allele1 in the case cohort like this：female het_mut *1 + female hom_mut *2 + male mut*1  is it right?

thank you 
best
