### ISSUE TITLE
Variant position column in PLINK 1.9 --pca var-wts file

### ISSUE THREAD

**Issue by yk-tanigawa** [chrchang/plink-ng#69]
Hi Chris, 

I am wondering if the output of variant weights from PLINK 1.9 PCA (`--pca var-wts`) can include the position of the variant.
It looks like the current output field has chromosome, variant ID, A1, and A2 in addition to variant loading to each of the component and the actual position of the variant is not present in the output.

I guess one can assign unique IDs to all the variants before applying PCA (`--set-missing-var-ids`), but I think it is nice to have the position column in the variant loading file from PCA as well.

**Comment by chrchang** [comment]
In plink 2.0, "--pca var-wts vcols=+pos" should do what you want.

plink 1.9's feature set was essentially frozen two years ago; the only things I plan to add there before formally ending beta testing are a few missing copy-number-variation functions, and a few extra guardrails (plink 2.0's new --bad-freqs flag will probably be backported).
