### ISSUE TITLE
Build failure on CentOS 6

### ISSUE THREAD

**Issue by outpaddling** [chrchang/plink-ng#72]
Yeah, I know it's an old OS, but it will still be around for a while in HPC.  I'm hoping to have all our systems upgraded to 7 by the end of this year.  In the meantime, it's a workhorse for us that I have to keep supporting.

Plus I'm using GCC 5.5, not the stock 4.4 suite from Yum.

There's a CentOS 6 VM here if you want to try reproducing the errors:

[http://www.peregrine.hpc.uwm.edu/vm.php](http://www.peregrine.hpc.uwm.edu/vm.php)

As root in the VM:

```
module load /sharedapps/pkg-2017Q4/etc/modulefiles/pkgsrc/2017Q4
cd /sharedapps/pkgsrc-2017Q4/wip
git pull
cd plink2
bmake

```
```
cc -c -O2 -g -DDYNAMIC_ZLIB -I/usr/pkg/include -I/usr/include -std=gnu99 -DNDEBUG -DZSTD_MULTITHREAD -Wall -Wextra -Wshadow -Wformat-security -Wdouble-promotion -Wfloat-conversion -Ihtslib -Ilibdeflate -Ilibdeflate/common -Izstd/lib -Izstd/lib/common -Izstd/zlibWrapper  -o libdeflate/lib/adler32.o libdeflate/lib/adler32.c
/tmp/ccHdgukk.s: Assembler messages:
/tmp/ccHdgukk.s:594: Error: suffix or operands invalid for `vpmaddubsw'
/tmp/ccHdgukk.s:599: Error: suffix or operands invalid for `vpaddd'
/tmp/ccHdgukk.s:604: Error: suffix or operands invalid for `vpsadbw'
/tmp/ccHdgukk.s:609: Error: suffix or operands invalid for `vpaddd'
/tmp/ccHdgukk.s:614: Error: suffix or operands invalid for `vpmaddwd'
/tmp/ccHdgukk.s:619: Error: suffix or operands invalid for `vpaddd'
/tmp/ccHdgukk.s:629: Error: suffix or operands invalid for `vphaddd'
/tmp/ccHdgukk.s:635: Error: suffix or operands invalid for `vphaddd'
/tmp/ccHdgukk.s:642: Error: no such instruction: `vextracti128 $0x1,%ymm1,%xmm1'
/tmp/ccHdgukk.s:652: Error: suffix or operands invalid for `vpslld'
/tmp/ccHdgukk.s:659: Error: suffix or operands invalid for `vpaddd'
/tmp/ccHdgukk.s:661: Error: suffix or operands invalid for `vphaddd'
/tmp/ccHdgukk.s:667: Error: suffix or operands invalid for `vphaddd'
/tmp/ccHdgukk.s:674: Error: no such instruction: `vextracti128 $0x1,%ymm3,%xmm3'
make: *** [libdeflate/lib/adler32.o] Error 1
*** Error code 2

```
Traced this one to x86/adler32_impl.h.  If I just comment out the #include, the file compiles.  Maybe that code should be guarded from the compiler on systems where it won't build?

Next error is similar:

```
cc -c -O2 -g -DDYNAMIC_ZLIB -I/usr/pkg/include -I/usr/include -std=gnu99 -DNDEBUG -DZSTD_MULTITHREAD -Wall -Wextra -Wshadow -Wformat-security -Wdouble-promotion -Wfloat-conversion -Ihtslib -Ilibdeflate -Ilibdeflate/common -Izstd/lib -Izstd/lib/common -Izstd/zlibWrapper  -o libdeflate/lib/deflate_decompress.o libdeflate/lib/deflate_decompress.c
/tmp/ccVRd3k7.s: Assembler messages:
/tmp/ccVRd3k7.s:2151: Error: no such instruction: `shlx %r12,0(%r13),%rax'
/tmp/ccVRd3k7.s:2430: Error: no such instruction: `shlx %r12,0(%r13),%rax'
/tmp/ccVRd3k7.s:2457: Error: no such instruction: `shrx %rdx,%rbx,%rbx'
/tmp/ccVRd3k7.s:2489: Error: no such instruction: `shlx %rax,%rdx,%rdx'
/tmp/ccVRd3k7.s:2531: Error: no such instruction: `shlx %eax,%r8d,%edx'
/tmp/ccVRd3k7.s:2543: Error: no such instruction: `shrx %rdx,%rbx,%rbx'
/tmp/ccVRd3k7.s:2566: Error: no such instruction: `shlx %r12,0(%r13),%rax'
/tmp/ccVRd3k7.s:2585: Error: no such instruction: `shrx %rax,%rbx,%rcx'
/tmp/ccVRd3k7.s:2590: Error: no such instruction: `shlx %eax,%r8d,%eax'
/tmp/ccVRd3k7.s:2617: Error: no such instruction: `shrx %rdi,%rcx,%rcx'
/tmp/ccVRd3k7.s:2628: Error: no such instruction: `shrx %rdx,%rcx,%rbx'
/tmp/ccVRd3k7.s:2633: Error: no such instruction: `shlx %edx,%r8d,%edx'
/tmp/ccVRd3k7.s:2839: Error: no such instruction: `shlx %edx,%r8d,%edi'
/tmp/ccVRd3k7.s:2896: Error: no such instruction: `shlx %rdi,0(%r13),%rdx'
/tmp/ccVRd3k7.s:3013: Error: no such instruction: `shlx %r12,0(%r13),%rcx'
/tmp/ccVRd3k7.s:3036: Error: no such instruction: `shrx %rdi,%rbx,%rbx'
/tmp/ccVRd3k7.s:3108: Error: no such instruction: `shlx %rdi,%rdx,%rdx'
/tmp/ccVRd3k7.s:3225: Error: no such instruction: `shlx %rcx,%rdi,%rdi'
/tmp/ccVRd3k7.s:3458: Error: no such instruction: `shlx %rax,%rcx,%rcx'
/tmp/ccVRd3k7.s:3495: Error: no such instruction: `shlx %rax,%rdx,%rdx'
make: *** [libdeflate/lib/deflate_decompress.o] Error 1
*** Error code 2

```
This one traced to x86/decompress_impl.h.

Next:

```
cc -c -O2 -g -DDYNAMIC_ZLIB -I/usr/pkg/include -I/usr/include -std=gnu99 -DNDEBUG -DZSTD_MULTITHREAD -Wall -Wextra -Wshadow -Wformat-security -Wdouble-promotion -Wfloat-conversion -Ihtslib -Ilibdeflate -Ilibdeflate/common -Izstd/lib -Izstd/lib/common -Izstd/zlibWrapper  -o zstd/lib/compress/huf_compress.o zstd/lib/compress/huf_compress.c
/tmp/ccXJYtAA.s: Assembler messages:
/tmp/ccXJYtAA.s:625: Error: no such instruction: `shlx %r14,%rsi,%rsi'
/tmp/ccXJYtAA.s:627: Error: no such instruction: `shlx %rcx,%r14,%rcx'
/tmp/ccXJYtAA.s:631: Error: no such instruction: `shlx %r15,%r9,%r9'
/tmp/ccXJYtAA.s:636: Error: no such instruction: `shlx %r10,%r9,%r9'
/tmp/ccXJYtAA.s:680: Error: no such instruction: `shrx %r11,%rax,%r11'
/tmp/ccXJYtAA.s:708: Error: no such instruction: `shlx %rcx,%rax,%rax'
/tmp/ccXJYtAA.s:807: Error: no such instruction: `shlx %rcx,%rax,%rax'
/tmp/ccXJYtAA.s:832: Error: no such instruction: `shlx %rcx,%rsi,%rsi'
/tmp/ccXJYtAA.s:876: Error: no such instruction: `shrx %r11,%rax,%r11'
make: *** [zstd/lib/compress/huf_compress.o] Error 1
*** Error code 2

```
I didn't trace this one, figured this should be enough info to get the point across.

Thanks,

    JB

**Comment by chrchang** [comment]
http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id2207/Intel_E5-2640v3_Haswell%3A_No_such....html suggests that the assembler on your system is out of sync with your compiler.  Have you tried using gcc 4.4?

**Comment by chrchang** [comment]
(or try to upgrade the assembler on the system to be in sync with 5.5)

**Comment by outpaddling** [comment]
I can work around it using either of these fixes, but there is definitely something special about the plink2 code.  The 5.5 compiler I'm using is provided by pkgsrc for its own use and successfully builds nearly 17,000 other packages (the vast majority of the pkgsrc collection) on CentOS 6.  I'll see if there's a clean way to force this package to use pkgsrc binutils for now.  Thanks...

**Comment by chrchang** [comment]
Probably a configuration/compiler flag issue.  If you've successfully built either libdeflate or zstd on CentOS 6 with the standard settings, can you post the compiler flags that are being used?

**Comment by outpaddling** [comment]
Although it requires a very unusual trigger, I'm viewing this as a compiler installation bug.  Attempting to patch the pkgsrc gcc5 package now so that it will use pkgsrc binutils instead of Yum's outdated binutils.  At least one other pkgsrc developer is warm to the idea.  Will keep you posted...

Also, pkgsrc has a zstd package that also fails to build:

cc -O2 -I/usr/pkg/include -I/usr/include -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls  -I/usr/pkg/include -I/usr/include -I. -I./common -DXXH_NAMESPACE=ZSTD_ -I./legacy -DZSTD_LEGACY_SUPPORT=4  -c -o compress/huf_compress.o compress/huf_compress.c
/tmp/cch6sHYh.s: Assembler messages:
/tmp/cch6sHYh.s:275: Error: no such instruction: `shlx %r14,%rsi,%rsi'
/tmp/cch6sHYh.s:277: Error: no such instruction: `shlx %rcx,%r14,%rcx'
/tmp/cch6sHYh.s:280: Error: no such instruction: `shlx %r15,%r9,%r9'
/tmp/cch6sHYh.s:284: Error: no such instruction: `shlx %r10,%r9,%r9'
/tmp/cch6sHYh.s:298: Error: no such instruction: `shrx %r11,%rax,%r11'
/tmp/cch6sHYh.s:305: Error: no such instruction: `shlx %rcx,%rax,%rax'
/tmp/cch6sHYh.s:359: Error: no such instruction: `shlx %rcx,%rax,%rax'
/tmp/cch6sHYh.s:367: Error: no such instruction: `shlx %rcx,%rsi,%rsi'
/tmp/cch6sHYh.s:380: Error: no such instruction: `shrx %r11,%rax,%r11'
make[1]: *** [compress/huf_compress.o] Error 1
make[1]: Leaving directory `/usr/pkgsrc/archivers/zstd/work/zstd-1.3.4/lib'
make: *** [allzstd] Error 2
*** Error code 2

**Comment by outpaddling** [comment]
I devised a couple of enhancements for the pkgsrc binutils and gcc* packages that will keep RHEL/CentOS 6 afloat for a while, at least with regard to this issue.
plink2 is now building successfully and the patches are under review pending commit.
