### ISSUE TITLE
--import-dosage generates malformed .pgen file (for a toy example)

### ISSUE THREAD

**Issue by robkar** [chrchang/plink-ng#73]
Hello,

I tried generating a tiny toy dataset for testing the --score command in the latest Plink 2.0, and ran into problems. Since I wanted dosages for testing, I hand-wrote a 2 SNP, 3 sample Plink 1 dosage file. This seemed to work fine in autoconversion to pgen format, but subsequent operations give me "Error: Malformed .pgen file."

How I generated the file set:
`plink2 --import-dosage data.dosage.txt format=1 skip2=2 chr-col-num=4 pos-col-num=5 --fam data.fam --out pform`

(I added CHR and POS columns to the dosage file because --map file info did not make it into the .pvar file when I tried it)

And then I got the error from running:
`plink2 --pfile pform --freq --out freqs`

Attaching logs and genotype files. Is this dataset just too tiny, or is there some other cause?

[dosage_malformed_pgen.zip](https://github.com/chrchang/plink-ng/files/2012670/dosage_malformed_pgen.zip)

**Comment by chrchang** [comment]
There have definitely been bugs before where most cases work but the smallest cases fail.  I'll take a look and try to post a fix today.

**Comment by chrchang** [comment]
Okay, looks like --import-dosage was more generally broken due to an off-by-one error introduced a few weeks ago.  Should be fixed now; let me know if you run into any more problems.

**Comment by robkar** [comment]
Yes, the May 17 version works for me now. Thank you!
