### ISSUE TITLE
Output discrepancy

### ISSUE THREAD

**Issue by outpaddling** [chrchang/plink-ng#74]
Little cosmetic issue:

plink2 seems to report that it's using the maximum available cores in spite of the --threads flag:

Using up to 32 threads (change this with --threads).
^M--dummy: 65k variants written.^M--dummy: 131k variants written.^M--dummy: 196k
 variants written.^M--dummy: 262k variants written.^M--dummy: 327k variants written.^M--dummy: 393k variants written.^M--dummy: 458k variants written.^M--dummy: 524k variants written.^M--dummy: 589k variants written.^M--dummy: 655k variants written.^M--dummy: 720k variants written.^M--dummy: 786k variants written.^M--dummy: 851k variants written.^M--dummy: 917k variants written.^M--dummy: 983k variants written.^MDummy data (9999 samples, 999999 SNPs) written to testdata.pgen + testdata.pvar
+ testdata.psam .
End time: Thu May 17 15:17:30 2018
/usr/local/bin/plink2

                          *** Trial 1 ***

===========================================================
Running --keep benchmark...
===========================================================

PLINK v2.00a2 64-bit (10 May 2018)             www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink2.log.
Options in effect:
  --keep id_subset.txt
  --make-pgen
  --pfile testdata
  --threads 16

**Comment by chrchang** [comment]
Are these in the same run?  I can't replicate this, and the code looks obviously correct.

**Comment by outpaddling** [comment]
Da, sorry.  They are in different runs.  I misread the boundaries in the output.  Time for a nap...
