### ISSUE TITLE
Minor FreeBSD patch

### ISSUE THREAD

**Issue by outpaddling** [chrchang/plink-ng#75]
```
--- plink2_base.h.orig  2018-05-11 05:21:46 UTC
+++ plink2_base.h
@@ -444,7 +444,7 @@ typedef uint32_t BoolErr;
 #  define FOPEN_RB "r"
 #  define FOPEN_WB "w"
 #  define FOPEN_AB "a"
-#  ifdef __APPLE__
+#  if defined(__APPLE__) || defined(__FreeBSD__)
 #    define fread_unlocked fread
 #    define fwrite_unlocked fwrite
 #  endif

```

**Comment by chrchang** [comment]
Ok, applied this.

**Comment by outpaddling** [comment]
Great, thanks.  Do you know why the unlocked functions are being used in the first place?  Seems they're not thread-safe and plink has been running without them on Darwin for some time.

From the Linux man page:

Description

Each of these functions has the same behavior as its counterpart without the "_unlocked" suffix, except that they do not use locking (they do not set locks themselves, and do not test for the presence of locks set by others) and hence are thread-unsafe. See flockfile(3).
Conforming To

The four functions getc_unlocked(), getchar_unlocked(), putc_unlocked(), putchar_unlocked() are in POSIX.1-2001.

The nonstandard *_unlocked() variants occur on a few UNIX systems, and are available in recent glibc. They should probably not be used.

**Comment by chrchang** [comment]
plink2 never has multiple threads trying to read/write from the same file handle, so it's always safe to use these functions when they exist.

**Comment by outpaddling** [comment]
Good enough, thanks.
