### ISSUE TITLE
Feature request: ignore duplicate rsIDs when using --score

### ISSUE THREAD

**Issue by sritchie73** [chrchang/plink-ng#80]
When `--score` encounters duplicate rsIDs it crashes with an error.

It would be helpful to provide some option(s) to handle duplicates. The most straightforward one, would be an option that allows `--score` to throw a warning and skip any duplicate rsIDs it encounters rather than crashing with an error.

**Comment by chrchang** [comment]
Okay, just posted an update which adds a 'ignore-dup-ids' modifier to --score; will provide prebuilt binaries tonight.

**Comment by sritchie73** [comment]
Thanks! Much appreciated
