### ISSUE TITLE
Feature request: --score option to flip allele on mismatch 

### ISSUE THREAD

**Issue by sritchie73** [chrchang/plink-ng#81]
Sometimes when calculating polygenic risk scores variants are "skipped due to a mismatching allele code", i.e. where the variant in the input genotype file has allele codes from the opposite strand to the allele codes present in the input score file.

it would be useful to have an additional option (`flip-on-mismatch`?) under which plink tries flipping the score allele code when it finds a variant where the score allele code isn't found for that variant in the input genotype data.

**Comment by chrchang** [comment]
This is outside --score's scope.  There is a single set of dedicated flipping functions; this is much cleaner than having separate flipping functionality for every major command.  I'm open to recommendations on making the dedicated flipping functions more useful, though.
