### ISSUE TITLE
logistic regression: all outputs are NA, if I provide a large number of samples

### ISSUE THREAD

**Issue by carbocation** [chrchang/plink-ng#85]
In the UK Biobank, I'm trying to run logistic regression on a custom-defined phenotype. If I `--thin-indiv-count` to < 100,000 samples or so, I will get some non-NA results. If I have enough samples, I get all NAs in my output. It seems that if the P value is less than some modest cutoff (not even genomewide significance), the result becomes NA.

Should I not be using plink2 for logistic regression yet?

```
PLINK v2.00a2LM AVX2 Intel (21 Aug 2018)       www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /home/jovyan/work/tiny.log.
Options in effect:
  --1
  --bfile ukbb-genotypes
  --chr 1
  --covar my-phenotypes
  --covar-name PC1-PC10,birthyear,Inferred_Gender,in_white_British_ancestry_subset
  --from-bp 700000
  --geno 0.1
  --glm hide-covar
  --hwe 1e-50
  --keep-if in_white_British_ancestry_subset == 1
  --maf 0.001
  --out /home/jovyan/work/tiny
  --pheno my-phenotypes
  --pheno-name My_Binary_Phenotype
  --require-covar
  --require-pheno
  --snps-only
  --to-bp 800000

Start time: Wed Aug 22 18:12:58 2018
60390 MiB RAM detected; reserving 30195 MiB for main workspace.
Using up to 16 threads (change this with --threads).
488377 samples (264863 females, 223511 males, 3 ambiguous; 488377 founders)
loaded from {censored}.
61866 out of 784256 variants loaded from
{censored}.
1 binary phenotype loaded (23154 cases, 464241 controls).
--remove-fam: 488375 samples remaining.
--require-pheno: 980 samples removed.
--thin-indiv-count: 287395 samples removed (200000 remaining).
13 covariates loaded from {censored}.
--require-covar: 0 samples removed.
--keep-if: 32187 samples removed.
167813 samples (90634 females, 77179 males; 167813 founders) remaining after
main filters.
8136 cases and 159677 controls remaining after main filters.
Calculating allele frequencies... done.
--geno: 2 variants removed due to missing genotype data.
--hwe: 5 variants removed due to Hardy-Weinberg exact test (founders only).
1 variant removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
4 variants remaining after main filters.
Covariates written to /home/jovyan/work/tiny.cov.
--glm logistic regression on phenotype 'My_Binary_Phenotype': done.
Results written to /home/jovyan/work/tiny.My_Binary_Phenotype.glm.logistic .
End time: Wed Aug 22 18:13:02 2018
Warning: Excluding constant covariate 'in_white_British_ancestry_subset' from --glm.
```

**Comment by chrchang** [comment]
Have you tried "--glm firth-fallback"?  This addresses a common scenario where plain logistic regression fails on an imbalanced phenotype.

If that still doesn't work, maybe plink2's logistic- and Firth-regression precision levels and convergence criteria don't work for your dataset.  In that case, if you can give me a (possibly fake) phenotype and a few variants which exhibit the same phenomenon of nonconvergence past ~100k samples, I can investigate the problem in more detail.

**Comment by carbocation** [comment]
I have tried firth-fallback, and the results are unfortunately unchanged. The case/control imbalance is such that about 5% of the UK Biobank has my binary phenotype. I get all NAs once I include somewhere between ~150k-200k samples in logistic regression.

Unfortunately, I can't send over a sample from the UK Biobank data. If your group has this data, I can send you a simulated phenotype.

**Comment by carbocation** [comment]
Of note, if I leave out age -- a covariate that is *strongly associated* with my phenotype, but which in no way could be used to separate cases from controls by itself -- I can get the model to run. Unfortunately, without an age covariate, the model results don't mean much.

**Comment by chrchang** [comment]
A simulated phenotype with the same property, a collection of covariates (pointers to UK Biobank data ok), and a list of variants will do.

**Comment by chrchang** [comment]
In the meantime, have you tried pre-transforming your phenotype by subtracting out a suitable multiple of age?  That might solve the immediate problem, though in that event it would still be useful to improve plink2 so that you'd be less likely to need to do this in the future.

**Comment by carbocation** [comment]
Yes, I will start by standardizing the age variable. (In particular, it's currently birthyear, so if there are issues around non-standardized variables, the current coding will exacerbate them.)

**Comment by carbocation** [comment]
After standardizing the birthyear variable, I was able to complete the analysis. For chromosome 1, for example, there were no "NA" values (all ~50,000 variants tested received a score).

**Comment by chrchang** [comment]
Since late January 2019, plink2 automatically tells you to use --covar-variance-standardize in this situation instead of proceeding with the regression.  (Also, since late July 2019, there has been a --glm cols=+err option to provide insight into any NA results that remain.)
