### ISSUE TITLE
A1_CASE_FREQ = inf for some SNPs with --glm and --vcf dosage=DS

### ISSUE THREAD

**Issue by robkar** [chrchang/plink-ng#89]
Hi,

I noticed that some SNPs in my association results from VCF data had inf values in A1_CASE_FREQ, even though A1_CASE_CT had a reasonable, finite, value. Also, the numbers in A1_CT and A1_FREQ are consistent with each other, but I don't get A1_CTRL_CT and A1_CTRL_FREQ to agree.

Is this a bug, or is there some quirk in my data that I'm not seeing?

Thanks

Attaching data, output , and log file.

[testcase_a1_case_freq.zip](https://github.com/chrchang/plink-ng/files/2348618/testcase_a1_case_freq.zip)

**Comment by chrchang** [comment]
This is a bug (when updating --glm to work with multiallelic variants, the line of code saving the case_allele_obs_ct denominator fell through the cracks); thanks for reporting it.  Should be fixed by commit 66f0434.
