### ISSUE TITLE
REF and ALT alleles swapped in output

### ISSUE THREAD

**Issue by rvernica** [chrchang/plink-ng#93]
The regression output seems to have the reference and alternate alleles swapped. Here is an example:
```
> plink2 --pfile plink2 --from rs13376177 --to rs13376177 --pheno input.txt --1 --out plink --pheno-col-nums 7 --glm 'cols=ref,alt1,alt,test'
PLINK v2.00a2LM 64-bit Intel (12 Sep 2018)     www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to plink.log.
Options in effect:
  --1
  --from rs13376177
  --glm cols=ref,alt1,alt,test
  --out plink
  --pfile plink2
  --pheno input.txt
  --pheno-col-nums 7
  --to rs13376177

Start time: Sat Oct 27 04:37:56 2018
378666 MiB RAM detected; reserving 189333 MiB for main workspace.
Using up to 96 threads (change this with --threads).
487409 samples (264319 females, 223008 males, 82 ambiguous; 487409 founders)
loaded from plink2.psam.
7402791 variants loaded from plink2.pvar.
1 binary phenotype loaded (43552 cases, 293599 controls).
--from/--to: 1 variant remaining.
Calculating allele frequencies... done.
1 variant remaining after main filters.
--glm logistic regression on phenotype 'PHENO1': done.
Results written to plink.PHENO1.glm.logistic .
End time: Sat Oct 27 04:37:58 2018
```
```
> head plink.PHENO1.glm.logistic
#ID	REF	ALT1	ALT	A1	TEST
rs13376177	G	C	C	G	ADD
```
For the [rs13376177](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=rs13376177) variant, the reference allele should be `C` and the alternate allele should be `G`. Am I missing something?

**Comment by chrchang** [comment]
How was plink2{.pgen,.pvar,.psam} generated?  plink2 only preserves the REF allele settings from the input files it's given; if the original source did not contain this information (e.g. it was a plink 1 fileset), you'll need to use --ref-allele (--ref-from-fa also works if all your variants are SNPs) to scrape the correct REF alleles.

**Comment by rvernica** [comment]
The index was generated using `plink2` like this:
```
> plink2 --sample foo.sample --bgen bar.bgen
```

**Comment by chrchang** [comment]
Oops, missed this response.

Use "--bgen bar.bgen ref-first" to specify that the REF allele comes first in the file.  The BGEN specification does not state whether REF is first or last.
