### ISSUE TITLE
Request to post release binaries

### ISSUE THREAD

**Issue by mwalker174** [chrchang/plink-ng#96]
Hello,

I was wondering if you could please post the latest binaries from https://www.cog-genomics.org/plink/2.0/ here on github (under Releases). I am developing a pipeline with Dockerfiles. One of them requires plink2 and it is failing because the URL to the October 2018 version is no longer available on aws. If possible, having a permanent github URL would be ideal.

Thanks in advance.

**Comment by chrchang** [comment]
While there's more work to do before declaring a beta release, I realize that the currently-posted Github release is far out of date, so I'll go ahead and create a "start of 2019" checkpoint.

**Comment by mwalker174** [comment]
Great, thank you!
