### ISSUE TITLE
Test data fails

### ISSUE THREAD

**Issue by outpaddling** [chrchang/plink-ng#97]
Is the test data currently up-to-date?  See run_tests.sh output below.

Also, should the binary be called "plink" or "plink2"?  Just want to be consistent for portability of scripts across different installation methods.

Thanks.

./run_tests.sh 
+ [[ 0 -eq 0 ]]
+ d=../../build_dynamic
+ cd TEST_EXTRACT_CHR
+ ./run_tests.sh ../../build_dynamic
+ plink --simulate simulate.txt --out tmp_data
Error: Unrecognized flag ('--simulate').
For more info, try 'plink2 --help [flag name]' or 'plink2 --help | more'.

**Comment by chrchang** [comment]
This is not a bug; plink 2.0 is not intended to be perfectly compatible with 1.x (and as a consequence, its binary should be “plink2”).

**Comment by outpaddling** [comment]
This is test data taken from the 2.0 subdirectory, though:

```
ls work/plink-ng-04c8182/2.0/Tests/
run_tests.sh           TEST_MAF_FILTER        TEST_SAMPLE_SUBSET
TEST_DOSAGE_ROUND_TRIP TEST_PGEN_FREQ
TEST_EXTRACT_CHR       TEST_PHASED_VCF
```
plink2 is will be, thanks.

**Comment by chrchang** [comment]
The plink 2.0 test assumes a plink 1.9 binary is available, and that “plink” points to the latter.

**Comment by chrchang** [comment]
(To elaborate, the test is verifying that plink 2.0's results are consistent with plink 1.9's.)

**Comment by outpaddling** [comment]
OK, I can work with that as long as the requirements are clear.  It would be nice to have a test suite that doesn't depend on another version of the program, though.  For now I'm installing the following wrapper script with my plink2 package:

```
#!/bin/sh -e

if ! which plink; then
    cat << EOM

You must install both plink and plink2 before running the plink2 tests.

EOM
    exit 1
fi

if [ -e plink2-Tests ]; then
    cat << EOM

plink2-Tests already exits.  Remove it first if you want to run $0.

EOM
    exit 1
fi

cp -R %%DATADIR%%/Tests plink2-Tests
cd plink2-Tests
./run_tests.sh
```
